Repository alchemy-fr/Phraseanet, pull requests merged in 2019-11, with the labels that each got.

#3197 PHRAS-2808 PHRAS-2806 disable cterms mask writable fields 4.1
  lib/Alchemy/Phrasea/Controller/Admin/FieldsController.php
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Prod/EditController.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Databox/Field/DbalDataboxFieldRepository.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
  lib/classes/databox.php
  lib/classes/databox/field.php
  lib/classes/patch/410alpha17a.php
  lib/conf.d/bases_structure.xml
  templates/web/admin/fields/templates.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Admin/FieldsTest.php
  www/scripts/models/field.js
  www/scripts/tests/specs/models.js
Labels: 4.1

#3188 PHRAS-2785 Port to 4.1 - Facets on date are restitued in a wicked way
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
Labels: 4.1

#3198 PHRAS-2792 Order manager : Applied choice not shown before order validation
  package.json
  resources/www/common/images/icons/to_be_denied.svg
  resources/www/common/images/icons/to_be_validated.svg
  yarn.lock
Labels: 4.1

#3181 PHRAS-2761 add status change to quarantine
  lib/Alchemy/Phrasea/Controller/Prod/LazaretController.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Lazaret.php
  lib/Alchemy/Phrasea/Model/Entities/LazaretFile.php
  lib/Alchemy/Phrasea/Model/Manipulator/LazaretManipulator.php
  resources/www/common/images/icons/icon-right-arrow.svg
  templates/web/prod/upload/lazaret.html.twig
Labels: 4.1

#3203 PHRAS-2809 Prod on editing window, hide field swith attribut "gui_editable" to false
  templates/web/prod/actions/edit_default.html.twig
Labels: 4.1

#3202 PHRAS-2811 : backport PHRAS-2748 :
  lib/Alchemy/Phrasea/SearchEngine/Elastic/StringUtils.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
Labels: 4.0

#3201 PHRAS-2760 help menue NOK in /view
  resources/www/permaview/styles/main.scss
Labels: 4.1

#3200 PHRAS-2748_bad-chars-cterms_4.1
  lib/Alchemy/Phrasea/SearchEngine/Elastic/StringUtils.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Thesaurus/CandidateTerms.php
Labels: 4.1

#3192 Kubernetes ready
  Dockerfile
  README.md
  build.sh
  docker/nginx/boot.sh
  docker/nginx/etc/nginx/nginx.conf
  docker/nginx/nginx.conf.sample
  docker/phraseanet/boot.sh
  docker/phraseanet/phraseanet-entrypoint.sh
  docker/phraseanet/worker-boot.sh
  yarn.lock
Labels: 4.1

#3210 PHRAS-2816 Hidden fields is roll over and detailled view
  lib/Alchemy/Phrasea/Controller/Admin/FieldsController.php
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Prod/EditController.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Databox/Field/DbalDataboxFieldRepository.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/classes/databox.php
  lib/classes/databox/field.php
  lib/conf.d/bases_structure.xml
  templates/web/admin/fields/templates.html.twig
  templates/web/common/macro_caption.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Admin/FieldsTest.php
  www/scripts/models/field.js
  www/scripts/tests/specs/models.js
Labels: 4.1

#3204 PHRAS-2815_generate-cterms-multi-db_4.1
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php
  tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/StructureTest.php
Labels: 4.1

#3211 PHRAS-2760 HELP menu : close submenu on click a div out of this
  templates/web/common/menubar.html.twig
Labels: 4.1

#3212 PHRAS-2749 Add missing cache directory
  cache/.gitkeep
Labels: 4.1

#3215 Embed README
  README.md
Labels: 4.1

#3218 autoinstall #comment check vars on auto-install
  docker/phraseanet/auto-install.sh
Labels: 4.1

#3220 PHRAS-2817 Update Dockerfile builds tools an 4.0
  Dockerfile
Labels: 4.0

#3216 PHRAS-2813 : 4.1 redis function delete is deprecated
  lib/Alchemy/Phrasea/Cache/RedisCache.php
  lib/Alchemy/Phrasea/Utilities/RedisSessionHandler.php
Labels: 4.1

#3217 PHRAS-2813 : 4.0 redis function delete is deprecated
  lib/Alchemy/Phrasea/Cache/RedisCache.php
  lib/Alchemy/Phrasea/Utilities/RedisSessionHandler.php
Labels: 4.0

#3214 PHRAS-2805 Port to 41 of Facet-case-sensibility
  lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/Escaper.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/FacetsResponse.php
  tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/ValueCheckerTest.php
Labels: 4.1

#3224 PHRAS-2831_port-truncation_4.1
  lib/Alchemy/Phrasea/SearchEngine/Elastic/AST/TextNode.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Mapping/StringFieldMapping.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContext.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Search/QueryContextFactory.php
  lib/Alchemy/Phrasea/SearchEngine/SearchEngineOptions.php
  tests/Alchemy/Tests/Phrasea/SearchEngine/AST/TextNodeTest.php
  tests/Alchemy/Tests/Phrasea/SearchEngine/Search/QueryContextTest.php
Labels: 4.1

#3219 PHRAS-2802_truncation-with-dots_4.0
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Index.php
Labels: 4.0

#3213 PHRAS-2824 Admin add string for Gui_editable and Gui_visible in admin
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/fields/templates.html.twig
Labels: 4.1

#3227 PHRAS-2830_space-in-query_4.1
  grammar/query.pp
Labels: 4.1

#3232 #comment README instruction to deploy the phraseanet stack
  README.md
Labels: 4.1

#3230 PHRDPL-81 #comment Use circle env vars CIRCLE_BRANCH
  .circleci/config.yml
Labels: 4.1

#3237 PHRAS-2834: When create a database from model, all fields have properties gui_editable gui_visible set to false
  lib/classes/databox.php
Labels: 4.1

#3236 PHRAS-2796 actionbar enhancements 4.1
  lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
  templates/web/prod/results/grid.html.twig
  templates/web/prod/results/list.html.twig
  templates/web/prod/results/record.html.twig
  templates/web/prod/results/records.html.twig
  templates/web/prod/toolbar.html.twig
Labels: 4.1

#3223 PHRAS-2829 Port 41 of Lightbox mobile: user choice and validation report
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.nl.xlf
  resources/www/lightbox/styles/jquery-mobile/_jquery-validator.scss
  resources/www/lightbox/styles/main-mobile.scss
  templates/mobile/lightbox/basket_element.html.twig
  templates/mobile/lightbox/sc_note.html.twig
  templates/mobile/lightbox/validate.html.twig
  templates/web/lightbox/basket_content_report.html.twig
  yarn.lock
Labels: 4.1

#3199 PHRAS-2810 Backport to 4.0 - Allow to disable cterms generation when a field is linked to a thesaurus Branch
  lib/Alchemy/Phrasea/Controller/Admin/FieldsController.php
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Prod/EditController.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Databox/Field/DbalDataboxFieldRepository.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/ThesaurusHydrator.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/Field.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Structure/GlobalStructure.php
  lib/classes/databox.php
  lib/classes/databox/field.php
  lib/conf.d/bases_structure.xml
  templates/web/admin/fields/index.html.twig
  templates/web/admin/fields/templates.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Admin/FieldsTest.php
  tests/Alchemy/Tests/Phrasea/SearchEngine/Structure/StructureTest.php
  www/scripts/models/field.js
  www/scripts/tests/specs/models.js
Labels: 4.0

#3226 PHRAS-1860 : Users / Push_list field to small in some cases
  lib/Alchemy/Phrasea/Model/Entities/User.php
Labels: 4.0

#3222 PHRAS-2814 : Elasticsearch informations on setup command line options are missing on master version
  lib/Alchemy/Phrasea/Command/Setup/Install.php
Labels: 4.1

#3107 PHRAS-2673 : release version 4.0.10
  bower.json
Labels: 4.0

#3206 PHRAS-2728 Fix langage selection on home backport to 4.0
  lib/Alchemy/Phrasea/Core/Event/Subscriber/PhraseaLocaleSubscriber.php
  tests/Alchemy/Tests/Phrasea/Core/Event/Subscriber/PhraseaLocaleSubscriberTest.php
Labels: 4.0

#3239 PHRAS-2829 lightbox hide list of users depending on right access
  templates/mobile/lightbox/sc_note.html.twig
  templates/web/lightbox/basket_content_report.html.twig
Labels: 4.1

#3240 PHRAS-1324 : libfaac abandonned
  lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
  lib/Alchemy/Phrasea/Media/Subdef/Video.php
  tests/classes/databox/subdefTest.php
Labels: 4.0

#3242 PHRAS-2829 Lightbox mobile : sort basket list + add user info
  resources/www/lightbox/styles/jquery-mobile/_jquery-validator.scss
  templates/mobile/common/menubar.html.twig
  templates/mobile/lightbox/basket_element.html.twig
  templates/mobile/lightbox/feed_element.html.twig
  templates/mobile/lightbox/index.html.twig
  templates/mobile/lightbox/validate.html.twig
Labels: 4.1

#3233 circleci #comment circleci refactor build
  .circleci/config.yml
Labels: 4.1, WIP

#3244 PHRDPL-82 #comment Optimize docker build speed
  .dockerignore
  Dockerfile
  Dockerfile-debug
  build.sh
Labels: 4.1

#3241 PHRAS-1324 : libfaac abandoned 4.1
  lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
  lib/Alchemy/Phrasea/Media/Subdef/Video.php
  tests/classes/databox/subdefTest.php
Labels: 4.1

#3243 PHRAS-2774 Prod answer grid: add margin-bottom (upgrade ppc@0.34.81-d)
  package.json
  yarn.lock
Labels: 4.1

#3246 PHRAS-2846 Prod-push window :fix button style
  package.json
  templates/web/prod/actions/Push.html.twig
  yarn.lock
Labels: 4.1

#3245 PHRAS-1154 :Migration 3.XX vers 4.XX - remove 'all' and 'last' in default query pref
  lib/Alchemy/Phrasea/Core/Version.php
  lib/classes/patch/410alpha19a.php
Labels: 4.1

#3248 Revert PHRAS-1324 libfaac abandoned 4.1
  lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
  lib/Alchemy/Phrasea/Media/Subdef/Video.php
  tests/classes/databox/subdefTest.php
Labels: 4.1
