Repository alchemy-fr/Phraseanet, pull requests merged in 2019-12, with the labels that each got.

#3258 PHRAS-2631_basket-feedback-icon
  lib/Alchemy/Phrasea/Controller/Prod/PushController.php
  resources/www/common/images/icons/basket_feedback_read.png
  resources/www/common/images/icons/basket_feedback_unread.png
  templates/web/prod/WorkZone/Macros.html.twig
Labels: 4.1

#3257 PHRAS-1324 : add libfdk_aac and add presets 4.0
  lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
  lib/Alchemy/Phrasea/Media/Subdef/Video.php
Labels: 4.0

#3250 PHRAS-1324 : add libfdk_aac and change presets name
  lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
  lib/Alchemy/Phrasea/Media/Subdef/Video.php
Labels: 4.1

#3252 PHRAS-2848 Lightbox mobile-Light design refacto 4.1
  package.json
  resources/www/lightbox/styles/jquery-mobile/_jquery-validator.scss
  templates/mobile/common/menubar.html.twig
  templates/mobile/lightbox/basket_element.html.twig
  templates/mobile/lightbox/index.html.twig
  yarn.lock
Labels: 4.1

#3261 PHRAS-2857 : Backport to 4.0 - Exclude some collections from quarantine checkers sha256, UUID, filename (AKA exclude Trash)
  lib/Alchemy/Phrasea/Border/Checker/AbstractChecker.php
  lib/Alchemy/Phrasea/Border/Checker/Filename.php
  lib/Alchemy/Phrasea/Border/Checker/Sha256.php
  lib/Alchemy/Phrasea/Border/Checker/UUID.php
  lib/Alchemy/Phrasea/Core/Provider/BorderManagerServiceProvider.php
  lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
  lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
  lib/classes/record/adapter.php
Labels: 4.0

#3263 PHRAS-2856 :fix record order in story 4.1
  lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
Labels: 4.1

#3260 PHRAS-2840 : Exclude collection from quarantine checker
  lib/Alchemy/Phrasea/Border/Checker/AbstractChecker.php
  lib/Alchemy/Phrasea/Border/Checker/Filename.php
  lib/Alchemy/Phrasea/Border/Checker/Sha256.php
  lib/Alchemy/Phrasea/Border/Checker/UUID.php
  lib/Alchemy/Phrasea/Core/Provider/BorderManagerServiceProvider.php
  lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
  lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
  lib/classes/record/adapter.php
Labels: 4.1

#3264 PHRAS-2848 Lightbox mobile-Light design refacto 4.1 - Fix audio display
  resources/www/lightbox/styles/main-mobile.scss
  templates/mobile/lightbox/basket_element.html.twig
Labels: 4.1

#3265 PHRAS-2821 : video portrait nok 4.1
  composer.json
  composer.lock
Labels: 4.1

#2734 PHRAS-2196 API / Stories record pagination on search answer and Stories fetch info
  lib/Alchemy/Phrasea/Application/ApiApplicationLoader.php
  lib/Alchemy/Phrasea/Controller/Api/Result.php
  lib/Alchemy/Phrasea/Controller/Api/V3Controller.php
  lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
  lib/Alchemy/Phrasea/Core/Event/Listener/OAuthListener.php
  lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
  lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
  lib/classes/record/adapter.php
Labels: 4.1, Enhancement, WIP

#3273 PHRAS-2814_missing-es-options-for-tests
  tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
  tests/bootstrap.sh
Labels: 4.1

#3266 PHRAS-2860 : Backport to 4.0 - Generated Subdefs for video Portait are not correctly Oriented 4.0
  composer.json
  composer.lock
Labels: 4.0

#3267 PHRAS-2859 #comment tests execution, corrupt conf 4.1
  tests/Alchemy/Tests/Phrasea/Command/Plugin/AddPluginTest.php
  tests/Alchemy/Tests/Phrasea/Command/Plugin/DisablePluginTest.php
  tests/Alchemy/Tests/Phrasea/Command/Plugin/EnablePluginTest.php
  tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
  tests/Alchemy/Tests/Phrasea/Controller/Prod/ExportTest.php
  tests/Alchemy/Tests/Phrasea/Core/CLIProvider/PluginServiceProviderTest.php
  tests/Alchemy/Tests/Phrasea/Core/Configuration/DisplaySettingServiceTest.php
  tests/Alchemy/Tests/Phrasea/Core/Event/Subscriber/DebuggerSubscriberTest.php
  tests/Alchemy/Tests/Phrasea/Core/Provider/AuthenticationManagerServiceProviderTest.php
  tests/Alchemy/Tests/Phrasea/Core/Provider/BorderManagerServiceProviderTest.php
  tests/Alchemy/Tests/Phrasea/Core/Provider/LocaleServiceProviderTest.php
  tests/Alchemy/Tests/Phrasea/Plugin/Management/AutoloaderGeneratorTest.php
  tests/Alchemy/Tests/Phrasea/Plugin/PluginManagerTest.php
Labels: 4.1

#3275 PHRAS-2706 Prod - Basket browser windows - Received basket filter basket
  lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php
Labels: 4.1

#3274 PHRAS-2861 Prod-Basket zone-Drop down menu-Preference
  templates/web/prod/index.html.twig
Labels: 4.1
