Repository alchemy-fr/Phraseanet, pull requests merged in 2020-07, with the labels that each got.

#3545 PHRAS-3151 upgrade mapbox lib
  package.json
  yarn.lock
Labels: 4.1, WIP

#3550 PHRAS-3151 upgrade phraseanet-production-client
  package.json
  yarn.lock
Labels: 4.1

#3549 PHRAS-3148 Thesaurus Guy : more design fix
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  resources/www/thesaurus/images/caret-right-solid-grey.svg
  resources/www/thesaurus/images/caret-right-solid.svg
  resources/www/thesaurus/styles/main.scss
  templates/web/thesaurus/new-term.html.twig
  templates/web/thesaurus/properties.html.twig
  templates/web/thesaurus/thesaurus.html.twig
Labels: 4.1, WIP

#3551 PHRAS-3158 adding missing env in phraseanet container
  docker-compose.yml
Labels: 4.1

#3552 PHRAS-3148 Thesaurus guy
  templates/web/thesaurus/properties.html.twig
  templates/web/thesaurus/thesaurus.html.twig
Labels: 4.1

#3554 PHRAS-3157 Prod - Video Tools - Thumbnail tab - some fix
  package.json
  templates/web/prod/actions/Tools/videoEditor.html.twig
  yarn.lock
Labels: 4.1

#3555 PHRAS-3163 Prod - Publication - Create publication - error in console when create
  package.json
  templates/web/prod/actions/publish/publish.html.twig
  yarn.lock
Labels: 4.1

#3557 PHRAS-3160 : Thesaurus - launch populate db - don't return elasticsearch detail in answer
  lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusController.php
Labels: 4.1

#3560 PHRAS-3167 set php and gateway timeout
  .env
  docker-compose.yml
  docker/nginx/root/entrypoint.sh
  docker/nginx/root/nginx.conf.sample
  docker/phraseanet/php.ini.sample
Labels: 4.1

#3553 PHRAS-3150 make optional for sync admin password
  .env
  docker-compose.yml
  docker/phraseanet/entrypoint.sh
Labels: 4.1

#3558 PHRAS-3164 lightbox - download action is NOK
  package.json
  resources/www/common/styles/main.scss
  resources/www/lightbox/styles/main.scss
  templates/web/common/dialog_export.html.twig
  templates/web/lightbox/index.html.twig
  templates/web/lightbox/index_layout.html.twig
  templates/web/lightbox/validate.html.twig
  yarn.lock
Labels: 4.1

#3562 PHRAS-3159 : Lazaret (quarantine) storage file path is not taken in account
  lib/Alchemy/Phrasea/Application.php
Labels: 4.1

#3564 PHRAS-3164 Lightbox : Remove key actions when modal is open
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  resources/www/lightbox/styles/main.scss
  templates/web/common/dialog_export.html.twig
  yarn.lock
Labels: 4.1

#3559 PHRAS-3162_es-document-is-empy-pdf_4.1
  lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
Labels: 4.1

#3565 PHRAS-3171 : Backport to 4.0 - Indexing - generate an error on a specific record pdf text extracted
  lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
Labels: 4.0

#3561 PHRAS-3169 Prod -video tools - Taken clip number from vtt when is present ideo subtitle with number
  package.json
  yarn.lock
Labels: 4.1

#3566 PHRAS-3173 change xpdf in favor of poppler-utils
  Dockerfile
Labels: 4.1

#3556 PHRAS-2504 : Ginger service integration Auto-subtitle
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Application.php
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Tools.php
  lib/Alchemy/Phrasea/Core/Event/Record/RecordAutoSubtitleEvent.php
  lib/Alchemy/Phrasea/Core/PhraseaEvents.php
  lib/Alchemy/Phrasea/Core/Provider/RepositoriesServiceProvider.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Model/Entities/WorkerJob.php
  lib/Alchemy/Phrasea/Model/Repositories/WorkerJobRepository.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/QueueWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php
  lib/Alchemy/Phrasea/WorkerManager/Queue/MessagePublisher.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/SubtitleSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/MainQueueWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
  lib/conf.d/configuration.yml
  templates/web/prod/actions/Tools/videoEditor.html.twig
Labels: 4.1, WIP

#3569 PHRAS-3177 prod - video tools - auto subtitling - add info about running autosubtitling request
  templates/web/prod/actions/Tools/videoEditor.html.twig
Labels: 4.1

#3570 PHRAS-3178 PHRASEANET_TRUSTED_PROXY env var
  docker/phraseanet/entrypoint.sh
Labels: 4.1

#3573 PHRAS-2504 : subtitling - translate
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  lib/Alchemy/Phrasea/Core/Event/Record/RecordAutoSubtitleEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/SubtitleSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
  templates/web/prod/actions/Tools/videoEditor.html.twig
Labels: 4.1

#3572 PHRAS-3167 - add timeout for cgi, proxy nginx and binaries parameters
  .env
  docker-compose.yml
  docker/nginx/root/entrypoint.sh
  docker/nginx/root/etc/nginx/nginx.conf
  docker/nginx/root/fastcgi_timeout.conf
  docker/nginx/root/nginx.conf.sample
  docker/phraseanet/entrypoint.sh
  docker/phraseanet/root/usr/local/etc/php-fpm.d/zz-docker.conf
Labels: 4.1, WIP

#3574 PHRAS-3170: all workers use WorkerRunningJob table
  lib/Alchemy/Phrasea/Core/Provider/RepositoriesServiceProvider.php
  lib/Alchemy/Phrasea/Model/Entities/WorkerRunningJob.php
  lib/Alchemy/Phrasea/Model/Entities/WorkerRunningPopulate.php
  lib/Alchemy/Phrasea/Model/Entities/WorkerRunningUploader.php
  lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
  lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningPopulateRepository.php
  lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningUploaderRepository.php
  lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/AssetsIngestSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/AssetsIngestWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/CreateRecordWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/DeleteRecordWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/ExportMailWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/PopulateIndexWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/PullAssetsWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/worker-manager/worker_info.html.twig
Labels: 4.1

#3580 Add UFRaw in Dockerfile to manipulate raw image formats
  Dockerfile
Labels: 4.1

#3581 PHRAS-3192 - add inkscape apt package to Dokerfile for svg files
  Dockerfile
Labels: 4.1

#3576 PHRAS-3181 : Worker video build subdefinition ended with error and tmp file is not copied to destination
  lib/Alchemy/Phrasea/Model/Entities/WorkerRunningJob.php
  lib/Alchemy/Phrasea/WorkerManager/Event/AssetsCreationRecordFailureEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Event/PopulateIndexFailureEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Event/SubdefinitionCreationFailureEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Event/SubdefinitionWritemetaEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/QueueWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/AssetsIngestSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/SearchengineSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/CreateRecordWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/PopulateIndexWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
  templates/web/admin/worker-manager/worker_info.html.twig
Labels: 4.1

#3490 PHRAS-3078 prod - redirect user on home when received 403 with "end session "
  resources/www/common/js/components/common.js
  templates/web/common/menubar.html.twig
  www/scripts/apps/admin/main/app.js
Labels: 4.1, WIP

#3578 PHRAS-3156 Prod - request map - memorise zoom level Between to search session
  package.json
  templates/web/prod/index.html.twig
  yarn.lock
Labels: 4.1, WIP

#3575 PHRAS-3117 Prod move video tools from action bar to local edit menu
  package.json
  templates/web/prod/actions/Tools/videoEditor.html.twig
  templates/web/prod/results/record.html.twig
  templates/web/prod/toolbar.html.twig
  yarn.lock
Labels: 4.1

#3582 PHRAS-3116 Prod - video-tools - Front for ask and edit subtitle or transcript generation
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
Labels: 4.1
