Repository alchemy-fr/Phraseanet, pull requests merged in 2020-03, with the labels that each got.

#3386 PHRAS-1661: remove application list in bin/console user:list
  lib/Alchemy/Phrasea/Command/User/UserListCommand.php
Labels: 4.1

#3388 PHRAS-1632 : 4.1 user:application , add client_secret on return
  lib/Alchemy/Phrasea/Command/User/UserApplicationsCommand.php
Labels: 4.1

#3384 PHRAS-2956 Account - developers - application - GUI create a desktop application
  package.json
  yarn.lock
Labels: 4.1

#3385 PHRAS-1648 : bin/console user:password
  bin/console
  lib/Alchemy/Phrasea/Command/User/UserPasswordCommand.php
  lib/Alchemy/Phrasea/Command/User/UserSetPasswordCommand.php
Labels: 4.1

#3340 PHRAS-2927_optimize-feedback-process_4.1
  lib/Alchemy/Phrasea/Controller/LightboxController.php
  lib/Alchemy/Phrasea/ControllerProvider/Lightbox.php
Labels: 4.1

#3383 PHRAS-2955 add doctrine metadata filesystem cache
  lib/Alchemy/Phrasea/Core/MetaProvider/DatabaseMetaProvider.php
Labels: 4.0

#3394 PHRAS-2970 Update redis domain property
  docker/phraseanet/auto-install.sh
Labels: 4.0

#3390 PHRAS-2961 Prod - Display ending date in feedback rollover and feedback deploy in workzone
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/Tooltip/Basket.html.twig
  templates/web/prod/WorkZone/Basket.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
Labels: 4.1

#3367 PHRDPL-44 merge phraseanet-docker repo to this one
  .dockerignore
  .env
  .gitignore
  Dockerfile
  Makefile
  README.md
  build.sh
  docker-compose.override.yml
  docker-compose.yml
  docker/caching/composer.json
  docker/caching/composer.lock
  docker/db/Dockerfile
  docker/db/docker/custom.cnf
  docker/db/docker/docker-entrypoint-initdb.d/01-create_databases.sql
  docker/db/docker/phraseanet-entrypoint.sh
  docker/elasticsearch/Dockerfile
  docker/nginx/boot.sh
  docker/nginx/root/entrypoint.sh
  docker/nginx/root/etc/nginx/nginx.conf
  docker/nginx/root/nginx.conf.sample
  docker/phraseanet-debug/entrypoint.sh
  docker/phraseanet-debug/usr/bin/docker-get-host-ip
  docker/phraseanet-debug/usr/bin/docker-xdebug-disable
  docker/phraseanet-debug/usr/bin/docker-xdebug-enable
  docker/phraseanet/auto-install.sh
  docker/phraseanet/boot.sh
  docker/phraseanet/entrypoint.sh
  docker/phraseanet/phraseanet-entrypoint.sh
  docker/phraseanet/root/usr/local/etc/php-fpm.d/www.conf.default
  docker/phraseanet/root/usr/local/etc/php-fpm.d/zz-docker.conf
  docker/phraseanet/worker-boot.sh
  docker/phraseanet/worker/entrypoint.sh
  resources/proxies/__CG__AlchemyPhraseaModelEntitiesBasket.php
  resources/proxies/__CG__AlchemyPhraseaModelEntitiesLazaretFile.php
Labels: 4.1

#3393 PHRAS-2964 : 4.1 change column size
  lib/Alchemy/Phrasea/Core/Version.php
  lib/conf.d/bases_structure.xml
Labels: 4.1

#3397 PHRAS-2974 more document formats for unoconv
  Dockerfile
Labels: 4.1

#3396 PHRAS-2967 Lightbox - dev of send email report - warn windows
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  resources/www/lightbox/styles/main-mobile.scss
  templates/mobile/common/menubar.html.twig
  templates/mobile/lightbox/index.html.twig
  templates/mobile/lightbox/validate.html.twig
  templates/web/lightbox/validate.html.twig
  yarn.lock
Labels: 4.1

#3392 PHRAS-2964 : 4.0 change column char size
  lib/conf.d/bases_structure.xml
Labels: 4.0

#3398 PHRAS-2976 : Migration Patch, transform old facette style to new one.
  lib/Alchemy/Phrasea/Core/Version.php
  lib/classes/patch/410alpha25a.php
Labels: 4.1

#3402 PHRAS-2979 : 4.0 The content of a story is not displayed even for users with appropriate on the collection
  lib/Alchemy/Phrasea/Helper/User/Edit.php
Labels: 4.0

#3400 PHRAS-2978 Feedback basket - Change date format lib for translation and UI fix
  lib/classes/phraseadate.php
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/Tooltip/Basket.html.twig
  templates/web/prod/WorkZone/Basket.html.twig
  yarn.lock
Labels: 4.1

#3399 PHRAS-2977 : Backport To 4.0 docker compose in Phraseanet repo
  .dockerignore
  .env
  .gitignore
  Dockerfile
  Makefile
  README.md
  build.sh
  docker-compose.override.yml
  docker-compose.yml
  docker/caching/composer.json
  docker/caching/composer.lock
  docker/db/Dockerfile
  docker/db/docker/custom.cnf
  docker/db/docker/docker-entrypoint-initdb.d/01-create_databases.sql
  docker/db/docker/phraseanet-entrypoint.sh
  docker/elasticsearch/Dockerfile
  docker/nginx/boot.sh
  docker/nginx/nginx.conf.sample
  docker/nginx/root/entrypoint.sh
  docker/nginx/root/etc/nginx/nginx.conf
  docker/nginx/root/nginx.conf.sample
  docker/phraseanet-debug/entrypoint.sh
  docker/phraseanet-debug/usr/bin/docker-get-host-ip
  docker/phraseanet-debug/usr/bin/docker-xdebug-disable
  docker/phraseanet-debug/usr/bin/docker-xdebug-enable
  docker/phraseanet/auto-install.sh
  docker/phraseanet/boot.sh
  docker/phraseanet/entrypoint.sh
  docker/phraseanet/phraseanet-entrypoint.sh
  docker/phraseanet/root/usr/local/etc/php-fpm.d/www.conf.default
  docker/phraseanet/root/usr/local/etc/php-fpm.d/zz-docker.conf
  docker/phraseanet/worker-boot.sh
  docker/phraseanet/worker/entrypoint.sh
Labels: 4.0

#3401 PHRAS-2981 - add dev utils to builder image
  .dockerignore
  .env
  Dockerfile
  README.md
  docker-compose.override.yml
  docker-compose.yml
  docker/builder/root/bootstrap/.oh-my-zsh/themes/alchemy.zsh-theme
  docker/builder/root/bootstrap/.zshrc
  docker/builder/root/bootstrap/entrypoint.d/ohmyzsh.sh
  docker/builder/root/bootstrap/entrypoint.d/zshrc.sh
  docker/builder/root/bootstrap/entrypoint.sh
  docker/phraseanet/entrypoint.sh
  docker/phraseanet/php.ini.sample
  docker/phraseanet/plugins/InitCommand.php
  docker/phraseanet/plugins/InstallCommand.php
  docker/phraseanet/plugins/SubCommand.php
  docker/phraseanet/plugins/console
  docker/phraseanet/worker/entrypoint.sh
  lib/Alchemy/Phrasea/Command/Plugin/AbstractPluginCommand.php
  tests/Alchemy/Tests/Phrasea/Command/Plugin/AddPluginTest.php
  yarn.lock
Labels: 4.1

#3405 PHRAS-2978 Feedback basket - enable to edit validation deadline
  lib/Alchemy/Phrasea/Controller/Prod/PushController.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Push.php
  lib/classes/phraseadate.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/Tooltip/Basket.html.twig
  templates/web/prod/WorkZone/Basket.html.twig
Labels: 4.1

#3404 PHRAS-2990 : Fix colluser for existing users - story right issue continuation of the ticket PHRAS-2979
  bin/console
  lib/Alchemy/Phrasea/Command/ApplyRightsCommand.php
  lib/classes/patch/4012.php
Labels: 4.0

#3173 PHRAS-2741 : worker service part 1
  bin/console
  lib/Alchemy/Phrasea/Border/Manager.php
  lib/Alchemy/Phrasea/Controller/Prod/ExportController.php
  lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
  lib/Alchemy/Phrasea/Controller/Prod/StoryController.php
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  lib/Alchemy/Phrasea/Core/Event/ExportMailEvent.php
  lib/Alchemy/Phrasea/Core/Event/Record/DeleteEvent.php
  lib/Alchemy/Phrasea/Core/Event/Record/RecordEvents.php
  lib/Alchemy/Phrasea/Core/Event/Record/SubdefinitionCreateEvent.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/ExportSubscriber.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/RecordEditSubscriber.php
  lib/Alchemy/Phrasea/Core/PhraseaEvents.php
  lib/Alchemy/Phrasea/Core/Provider/WorkerConfigurationServiceProvider.php
  lib/Alchemy/Phrasea/Media/SubdefGenerator.php
  lib/Alchemy/Phrasea/Media/SubdefSubstituer.php
  lib/Alchemy/Phrasea/Model/Manipulator/WebhookEventManipulator.php
  lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
  lib/Alchemy/Phrasea/Webhook/WebhookPublisher.php
  lib/Alchemy/Phrasea/Webhook/WebhookPublisherInterface.php
  lib/classes/record/adapter.php
  tests/Alchemy/Tests/Phrasea/Controller/Prod/ExportTest.php
Labels: 4.1, WIP

#3174 PHRAS-2739 : incorporate Phraseanet-plugin-SubdefWebhook into Phraseanet
  lib/Alchemy/Phrasea/Core/Event/Subscriber/WebhookSubdefEventSubscriber.php
  lib/Alchemy/Phrasea/Core/Provider/WebhookServiceProvider.php
  lib/Alchemy/Phrasea/Webhook/EventProcessorFactory.php
  lib/Alchemy/Phrasea/Webhook/Processor/SubdefEventProcessor.php
  tests/Alchemy/Tests/Phrasea/Model/Repositories/WebhookEventRepositoryTest.php
Labels: 4.1, WIP

#3172 PHRAS-2680 : webhook privacy and security in worker context
  lib/Alchemy/Phrasea/Account/AccountService.php
  lib/Alchemy/Phrasea/Authentication/RegistrationService.php
  lib/Alchemy/Phrasea/Controller/Admin/UserController.php
  lib/Alchemy/Phrasea/Controller/Root/AccountController.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/FeedEntrySubscriber.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/OrderSubscriber.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/WebhookUserEventSubscriber.php
  lib/Alchemy/Phrasea/Core/Event/User/DeletedEvent.php
  lib/Alchemy/Phrasea/Helper/User/Edit.php
  lib/Alchemy/Phrasea/Model/Entities/WebhookEvent.php
  lib/Alchemy/Phrasea/Model/Manipulator/UserManipulator.php
  lib/Alchemy/Phrasea/Model/Manipulator/WebhookEventManipulator.php
  lib/Alchemy/Phrasea/Order/Controller/BaseOrderController.php
  lib/Alchemy/Phrasea/Order/OrderDelivery.php
  lib/Alchemy/Phrasea/Order/ValidationNotifier.php
  lib/Alchemy/Phrasea/Order/ValidationNotifier/CompositeNotifier.php
  lib/Alchemy/Phrasea/Order/ValidationNotifier/MailNotifier.php
  lib/Alchemy/Phrasea/Order/ValidationNotifier/WebhookNotifier.php
  lib/Alchemy/Phrasea/Webhook/Processor/FeedEntryProcessor.php
  tests/Alchemy/Tests/Phrasea/Functional/UserDeletionTest.php
  tests/Alchemy/Tests/Phrasea/Webhook/Processor/FeedEntryProcessorTest.php
Labels: 4.1, WIP

#3403 PHRAS-2979 : 4.1 The content of a story is not displayed even for users with appropriate on the collection
  bin/console
  lib/Alchemy/Phrasea/Command/ApplyRightsCommand.php
  lib/Alchemy/Phrasea/Helper/User/Edit.php
  lib/classes/record/adapter.php
Labels: 4.1

#3406 PHRAS-2989 Prod - Detailed view - link in basket, store etc ... requires a double click
  package.json
  templates/web/prod/preview/appears_in.html.twig
  yarn.lock
Labels: 4.1

#3408 PHRAS-2978 Feedback basket - Change date format lib for translation and UI fix
  package.json
  templates/web/prod/WorkZone/Basket.html.twig
  yarn.lock
Labels: 4.1

#3409 PHRAS-2989 Prod - Detailed view - link in basket
  templates/web/prod/preview/short_history.html.twig
Labels: 4.1

#3410 PHRAS-2978 Feedback basket - Fix on feedback count display
  package.json
  yarn.lock
Labels: 4.1

#3414 PHRAS-2975 - add ffmpeg to docker image
  .dockerignore
  Dockerfile
Labels: 4.1

#3413 PHRAS-2997 Matomo analytic service in Phraseanet core
  cache/.gitkeep
  lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
  lib/Alchemy/Phrasea/Form/Configuration/GeneralFormType.php
  resources/hudson/_GV.php
  templates/mobile/common/index.html.twig
  templates/mobile/common/matomo_analytics.html.twig
  templates/web/common/index_bootstrap.html.twig
  templates/web/common/indexfloat.html.twig
  templates/web/common/matomo_analytics.html.twig
  templates/web/login/layout/base-layout.html.twig
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-with-hosts.yml
Labels: 4.1
