Repository alchemy-fr/Phraseanet, pull requests merged in 2020-09, with the labels that each got.

#3605 PHRAS-3188 Prod - Expose front in Phraseanet (To merge to pull/3579 )
  package.json
  templates/web/prod/WorkZone/ExposeEdit.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
  templates/web/prod/index.html.twig
  templates/web/prod/tab_headers.html.twig
  yarn.lock
Labels: 4.1

#3602 PHRAS-3209 JS Error message during upload: "img.toDataURL is not a function" on 4.0.12
  templates/web/prod/upload/upload.html.twig
Labels: 4.0

#3604 PHRAS-3212 Port 4.1 - JS Error message during upload: "img.toDataURL is not a function"
  package.json
  yarn.lock
Labels: 4.1

#3563 PHRAS-3174_api-v3-records_4.1
  API_documentation/v3/api.yaml
  API_documentation/v3/responses.yaml
  API_documentation/v3/schemas.yaml
  lib/Alchemy/Phrasea/Controller/Api/Result.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3ResultHelpers.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3SearchController.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3StoriesController.php
  lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
  lib/Alchemy/Phrasea/Databox/Record/LegacyRecordRepository.php
  lib/Alchemy/Phrasea/Databox/Record/RecordRepository.php
  lib/Alchemy/Phrasea/Helper/JsonBodyHelper.php
  lib/Alchemy/Phrasea/Search/StoryView.php
  lib/Alchemy/Phrasea/Search/V3SearchResultTransformer.php
  lib/Alchemy/Phrasea/Search/V3StoryTransformer.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticSearchEngine.php
  lib/classes/record/adapter.php
Labels: 4.1, WIP

#3610 PHRAS-3220 chown datas in background
  docker/phraseanet/entrypoint.sh
Labels: 4.1

#3611 PHRAS-3174_api-v3-records_4.1 (doc only)
  API_documentation/v3/api.yaml
  API_documentation/v3/schemas.yaml
Labels: 4.1
