Repository alchemy-fr/Phraseanet, pull requests merged in 2020-04, with the labels that each got.

#3419 PHRAS-3003 truncate large value to 32k
  lib/Alchemy/Phrasea/SearchEngine/Elastic/RecordHelper.php
Labels: 4.0

#3422 PHRAS-2999 prod - answer grid - hide selection summary
  lib/Alchemy/Phrasea/Controller/Prod/QueryController.php
Labels: 4.1

#3423 PHRAS-3005 Prod - workzone - error when expand feedback.
  templates/web/prod/Tooltip/Basket.html.twig
  templates/web/prod/WorkZone/Basket.html.twig
Labels: 4.1

#3424 PHRAS-2992 Prod Fix Date translation everywhere record history.
  lib/classes/phraseadate.php
Labels: 4.1

#3416 PHRAS-3001_es-geopoint-sources_4.1
  lib/Alchemy/Phrasea/Core/Provider/SearchEngineServiceProvider.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/DataboxFetcherFactory.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/GpsPosition.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Hydrator/MetadataHydrator.php
Labels: 4.1

#3421 PHRAS-3002 : Build subdef with fdk_aac NOK with ffmpeg 4.2.2 on Docker.
  composer.json
  composer.lock
  docker/phraseanet/entrypoint.sh
Labels: 4.1

#3407 PHRAS-2937 replace libmp3aac by libfdk_aac in databox model
  lib/conf.d/data_templates/DublinCore.xml
  lib/conf.d/data_templates/en-simple.xml
  lib/conf.d/data_templates/fr-simple.xml
Labels: 4.1

#3395 PHRAS-2972 Update Readme
  README.md
Labels: 4.1

#3425 PHRAS-3006 Port to 41 : front delete 3 by 3
  lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
  lib/Alchemy/Phrasea/Controller/RecordsRequest.php
  lib/Alchemy/Phrasea/Model/Converter/BasketConverter.php
  lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
  package.json
  resources/locales/messages.de.xlf
  resources/locales/validators.de.xlf
  templates/web/prod/actions/delete_records_confirm.html.twig
  templates/web/prod/actions/delete_records_confirm_form.html.twig
  yarn.lock
Labels: 4.1, WIP

#3430 PHRAS-3017 Backport to 4.0 sb31 craches indexer
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php
Labels: 4.0

#3431 PHRAS-3018_reject-php32_4.1
  lib/Alchemy/Phrasea/Command/Setup/Install.php
Labels: 4.1

#3427 PHRAS-3007 Geoloc configuration field section replace 'lng' by 'lon'
  lib/conf.d/configuration.yml
  package.json
  yarn.lock
Labels: 4.1

#3437 PHRAS-3023_slow-query-while-indexing_4.1
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/RecordListFetcherDelegate.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/ScheduledFetcherDelegate.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
Labels: 4.1

#3429 PHRAS-3015_sb31-crashes-indexer_4.1
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/RecordIndex.php
Labels: 4.1

#3433 PHRAS-3021 add volumes www-custom and cache
  .env
  docker-compose.override.yml
  docker-compose.yml
  docker/phraseanet/auto-install.sh
  docker/phraseanet/entrypoint.sh
Labels: 4.1

#3435 PHRAS-3019 4.1 More options for setup storage during install - set download lazaret
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Command/Setup/Install.php
  lib/Alchemy/Phrasea/Controller/Prod/UploadController.php
  lib/Alchemy/Phrasea/Controller/SetupController.php
  lib/Alchemy/Phrasea/Media/SubdefGenerator.php
  lib/Alchemy/Phrasea/Setup/Installer.php
  lib/conf.d/configuration.yml
  tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
  tests/Alchemy/Tests/Phrasea/Setup/InstallerTest.php
Labels: 4.1

#3426 PHRAS-3008_multiple-definitions-warnings_4.1
  lib/Alchemy/Phrasea/Plugin/Management/ComposerInstaller.php
Labels: 4.1

#3438 PHARS-3021 Remove rabbitmq from configuration.yml
  lib/conf.d/configuration.yml
Labels: 4.1

#3434 PHRAS-3014:Prod - Editing Confirm before filling field, latitude and longitude
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/edit_default.html.twig
  yarn.lock
Labels: 4.1

#3441 PHRAS-3025 : send Phraseanet log on stdout
  docker/phraseanet/entrypoint.sh
  docker/phraseanet/root/usr/local/etc/php-fpm.d/zz-docker.conf
Labels: 4.1

#3442 PHRAS-3022 prod - editing - add button for select all records of story and desing fix
  lib/Alchemy/Phrasea/Controller/RecordsRequest.php
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/edit_default.html.twig
  yarn.lock
Labels: 4.1

#3443 PHRAS-3027 : Backport To 4.0 - Populate - Slow query - due to LIMIT 508600, 200
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/RecordListFetcherDelegate.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/ScheduledFetcherDelegate.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
  lib/classes/patch/4012.php
  lib/conf.d/bases_structure.xml
Labels: 4.0

#3440 PHRAS-3023_slow-query-while-indexing_4.1
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/ElasticsearchOptions.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Delegate/RecordListFetcherDelegate.php
  lib/Alchemy/Phrasea/SearchEngine/Elastic/Indexer/Record/Fetcher.php
  lib/classes/patch/410alpha26a.php
  lib/conf.d/bases_structure.xml
Labels: 4.1

#3428 PHRAS-3012 : Backport to 4.0 last modification on docker-compose
  .dockerignore
  .env
  Dockerfile
  README.md
  composer.json
  composer.lock
  config/configuration.sample.yml
  docker-compose.override.yml
  docker-compose.yml
  docker/builder/root/bootstrap/.oh-my-zsh/themes/alchemy.zsh-theme
  docker/builder/root/bootstrap/.zshrc
  docker/builder/root/bootstrap/entrypoint.d/ohmyzsh.sh
  docker/builder/root/bootstrap/entrypoint.d/zshrc.sh
  docker/builder/root/bootstrap/entrypoint.sh
  docker/phraseanet/auto-install.sh
  docker/phraseanet/entrypoint.sh
  docker/phraseanet/php.ini.sample
  docker/phraseanet/plugins/InitCommand.php
  docker/phraseanet/plugins/InstallCommand.php
  docker/phraseanet/plugins/SubCommand.php
  docker/phraseanet/plugins/console
  docker/phraseanet/root/usr/local/etc/php-fpm.d/zz-docker.conf
  docker/phraseanet/worker/entrypoint.sh
  lib/Alchemy/Phrasea/Command/Plugin/AbstractPluginCommand.php
  lib/Alchemy/Phrasea/Command/Plugin/AddPlugin.php
  lib/Alchemy/Phrasea/Command/Setup/Install.php
  lib/Alchemy/Phrasea/Controller/SetupController.php
  lib/Alchemy/Phrasea/Media/SubdefGenerator.php
  lib/Alchemy/Phrasea/Setup/Installer.php
  lib/conf.d/configuration.yml
  tests/Alchemy/Tests/Phrasea/Command/Plugin/AddPluginTest.php
  tests/Alchemy/Tests/Phrasea/Command/Setup/InstallTest.php
  tests/Alchemy/Tests/Phrasea/Setup/InstallerTest.php
Labels: 4.0

#3445 PHRAS-2669 Prod set default color selection to vivid color
  package.json
  templates/web/prod/WorkZone/Macros.html.twig
  templates/web/prod/WorkZone/Story.html.twig
  templates/web/prod/index.html.twig
  yarn.lock
Labels: 4.1

#3447 PHRAS-2991 Prod - Sharing screen : Sharing to Twitter NOK
  templates/web/prod/Share/record.html.twig
Labels: 4.1

#3446 PHRAS-2888 remove unused strings
  lib/Alchemy/Phrasea/Controller/Prod/PushController.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/Basket.html.twig
  templates/web/prod/WorkZone/Browser/Results.html.twig
Labels: 4.1

#3449 PHRAS-2669 upgrade phraseanet-production-client
  package.json
  yarn.lock
Labels: 4.1

#3448 PHRAS-2184 : 4.1 list manager email domain filter
  lib/Alchemy/Phrasea/Controller/Prod/PushController.php
  lib/classes/User/Query.php
  templates/web/prod/actions/Feedback/list.html.twig
Labels: 4.1

#3452 PHRAS-2963 prod - publication reader - suscribing to a feed - refacto design windows
  lib/Alchemy/Phrasea/Controller/Prod/FeedController.php
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  yarn.lock
Labels: 4.1

#3451 PHRAS-3033 Prod - 500 error when click on "Tools" (action bar) with a story in selection.
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
Labels: 4.1

#3455 PHRAS-3035 Prod - videotools - change save message
  package.json
  yarn.lock
Labels: 4.1

#3450 PHRAS-3031: user account - remove space at end of email adress
  lib/Alchemy/Phrasea/Controller/Root/AccountController.php
  lib/Alchemy/Phrasea/Controller/Root/LoginController.php
  lib/Alchemy/Phrasea/Helper/User/Edit.php
  lib/Alchemy/Phrasea/Helper/User/Manage.php
Labels: 4.1

#3456 PHRAS-3037 Prod - Query with map - at reload the map box circle generate an error
  package.json
  yarn.lock
Labels: 4.1

#3459 PHRAS-3041 Admin - connected user - roll over on user - user info - css is NOK
  templates/web/admin/connected-users.html.twig
Labels: 4.1

#3460 PHRAS-3042 Admin - User edit - keep right pict always visible.
  templates/web/admin/editusers.html.twig
Labels: 4.1

#3461 PHRAS-1071 : 4.1 Prod / detailled view / basket link
  lib/Alchemy/Phrasea/Model/Repositories/BasketRepository.php
Labels: 4.1

#3458 PHRAS-2851 Lightbox - Feedback desktop: not possible to see the reviews summary
  package.json
  resources/www/lightbox/styles/main.scss
  templates/web/lightbox/agreement_box.html.twig
  templates/web/lightbox/validate.html.twig
  templates/web/prod/WorkZone/Basket.html.twig
  yarn.lock
Labels: 4.1

#3462 PHRAS-3043 Prod - After launch upload overlay in Prod - In editing, panels model, thesaurus, geonames, geoloc is NOK
  package.json
  yarn.lock
Labels: 4.1

#3463 PHRAS-3048 re-adding cache directory on 4.1
  cache/.gitkeep
Labels: 4.1
