Repository alchemy-fr/Phraseanet, pull requests merged in 2020-05, with the labels that each got.

#3466 PHRAS-3044: Prod - Video editor - Design language fix and default title of chapter
  package.json
  templates/web/prod/index.html.twig
  yarn.lock
Labels: 4.1

#3464 PHRAS-3047 front of - tools- metadatas tab - Add dropdown , fix design and refresh data.
  lib/Alchemy/Phrasea/Controller/Prod/SubdefsController.php
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/Tools/index.html.twig
  templates/web/prod/actions/Tools/metadata.html.twig
  yarn.lock
Labels: 4.1

#3467 PHRAS-3052 Prod - tools - Enable- Disable permalink Is NOK
  package.json
  yarn.lock
Labels: 4.1

#3468 PHRAS-3054 : Prod - Search for users in Pusch and Feedback is made on Login only, extend it to other fields
  lib/Alchemy/Phrasea/Controller/Prod/PushController.php
Labels: 4.1

#3469 PHRAS-3030 : Strings are Missing - translations are not possible in weblate - v4.1
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/databases.html.twig
  templates/web/prod/WorkZone/Basket.html.twig
  templates/web/prod/WorkZone/Story.html.twig
  templates/web/prod/actions/Property/index.html.twig
  templates/web/prod/index.html.twig
  templates/web/report/report_layout_child.html.twig
  yarn.lock
Labels: 4.1

#3471 PHRAS-3056 Prod - Push and Feedback - searching user is NOK , javascirpt error
  templates/web/prod/templates/push.html.twig
Labels: 4.1

#3472 PHRAS-3051 Prod - video tools - define a thumbnail for video don't update other static image like poster
  package.json
  templates/web/prod/actions/Tools/videoEditor.html.twig
  yarn.lock
Labels: 4.1

#3457 PHRAS-2524 : put worker log to ELK
  .gitignore
  config/filebeat.yml
  config/logstash.conf
  docker-compose.override.yml
Labels: 4.1

#3473 PHRAS-3059 String is missing in weblate - Prod - Actions button
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/Basket.html.twig
Labels: 4.1

#3478 PHRAS-3066 Prod - Tools - 500 error when record selection contains more than one record
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  templates/web/prod/actions/Tools/index.html.twig
Labels: 4.1

#3477 PHRAS-3062 Prod - Push feedback - The created user is not add to the current push or feedback
  package.json
  yarn.lock
Labels: 4.1

#3479 PHRAS-3063 Prod - Reorder documents in basket: Design issues
  package.json
  yarn.lock
Labels: 4.1

#3480 PHRAS-2157 Prod / Share : Iframe sizes are set to 0 for audio documents
  templates/web/prod/Share/record.html.twig
Labels: 4.1

#3483 PHRAS-3067 Prod - video tools - by default option "No Chapters Overlaps" need to be true
  templates/web/prod/actions/Tools/videoEditor.html.twig
Labels: 4.1

#3484 PHRAS-3068 Prod - publication -editing - title and subtile is not update after modification
  package.json
  yarn.lock
Labels: 4.1

#3485 PHRAS-3070 Prod publication - gif are played and check behavior in 4.0
  package.json
  templates/web/prod/results/item.html.twig
  templates/web/prod/results/record.html.twig
  yarn.lock
Labels: 4.1

#3487 PHRAS-3072 Several Design fix on production client before 4.1.0 release
  lib/Alchemy/Phrasea/Controller/Prod/FeedController.php
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/Browser/Browser.html.twig
  templates/web/prod/WorkZone/Browser/Results.html.twig
  templates/web/prod/actions/publish/publish.html.twig
  templates/web/prod/actions/publish/publish_edit.html.twig
  templates/web/prod/results/entry.html.twig
  templates/web/prod/results/feeds_entry.html.twig
  yarn.lock
Labels: 4.1

#3491 PHRAS-3074_url-detection-4.1
  lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php
Labels: 4.1

#3493 PHRAS-3073 Prod - Basket Feedback - add type (image, video...) on each basket items
  lib/Alchemy/Phrasea/Core/Configuration/DisplaySettingService.php
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/Macros.html.twig
  templates/web/prod/index.html.twig
  yarn.lock
Labels: 4.1

#3494 PHRAS-3082 Admin - design improvement - Invert sort on table "running job" , add icon to worker and search engine
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  resources/www/admin/images/cogs-solid.svg
  resources/www/admin/images/searchengin.svg
  resources/www/admin/images/tools-solid.svg
  resources/www/admin/styles/main.scss
  templates/web/admin/tree.html.twig
  templates/web/admin/worker-manager/index.html.twig
  templates/web/admin/worker-manager/worker_configuration.html.twig
  templates/web/admin/worker-manager/worker_info.html.twig
  templates/web/admin/worker-manager/worker_metadata.html.twig
  templates/web/admin/worker-manager/worker_pull_assets.html.twig
  templates/web/admin/worker-manager/worker_searchengine.html.twig
  templates/web/admin/worker-manager/worker_subview.html.twig
Labels: 4.1

#3496 PHRAS-3084 Admin - User - users edit all read right and all admin right in one click
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  resources/www/admin/images/database-solid-blue.svg
  resources/www/admin/images/database-solid.svg
  resources/www/admin/styles/main.scss
  resources/www/common/images/icons/check-square-regular.svg
  resources/www/common/images/icons/square-duotone.svg
  resources/www/common/images/icons/square-regular.svg
  templates/web/admin/editusers.html.twig
  templates/web/admin/index.html.twig
  templates/web/admin/tree.html.twig
Labels: 4.1

#3498 PHRAS-2404 : removed phpexiftool/exiftool unused in composer.lock
  composer.lock
Labels: 4.1

#3499 PHRAS-2404 : remove unused phpexiftool/exiftool in composer.lock
  composer.lock
Labels: 4.0

#3495 PHRAS-2393 : Port to 4.1 Archive task Improvement Nov 2018 PHRAS-2231 PHRAS-2233
  lib/Alchemy/Phrasea/TaskManager/Job/ArchiveJob.php
  lib/classes/databox/status.php
Labels: 4.1

#3492 PHRAS-3034 : Configuration.yml Migration patch for geoloc section, video editor and binaries timeout section
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Setup/Installer.php
  lib/classes/patch/410alpha28a.php
  lib/conf.d/configuration.yml
Labels: 4.1

#3503 PHRAS-3096 prod - uploader remove flash uploader
  templates/web/prod/upload/upload.html.twig
Labels: 4.1

#3504 PHRAS-3097 Prod - Editing - preview in video case - call embed-bundle player not the video editor
  package.json
  yarn.lock
Labels: 4.1

#3507 PHRAS-3049 More setup in docker-compose
  .env
  docker-compose.override.yml
  docker-compose.yml
  docker/phraseanet/auto-install.sh
  docker/phraseanet/entrypoint.sh
  lib/conf.d/configuration.yml
  lib/conf.d/data_templates/DublinCore.xml
Labels: 4.1, WIP

#3506 PHRAS-3088 : fix mysql server gone away and dead lock on table worker
  lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
Labels: 4.1

#3508 PHRAS-3091 : Back dev for add "content" operator when search users
  lib/Alchemy/Phrasea/Helper/User/Manage.php
  lib/classes/User/Query.php
  templates/web/admin/users.html.twig
Labels: 4.1

#3510 PHRAS-3105 Prod - tools - ask for re building subdef - Optim or Quick fix
  package.json
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/Tools/index.html.twig
  yarn.lock
Labels: 4.1

#3511 PHRAS-3086 workers : Jobs tab Refresh list on changing filters
  templates/web/admin/worker-manager/worker_info.html.twig
Labels: 4.1

#3512 PHRAS-3108 Prod - User pref - Add icon arround thumbnail size slider
  package.json
  templates/web/prod/index.html.twig
  yarn.lock
Labels: 4.1
