Repository alchemy-fr/Phraseanet, pull requests merged in 2021-03, with the labels that each got.

#3740 PHRAS-3388 Prod - Baskets - Validation Basket - Improve validation UX - show feedback result in Detailed view
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/record/recordPreview/index.js
  Phraseanet-production-client/src/skins/style/ui-components/_modal-preview.scss
  lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
  lib/Alchemy/Phrasea/Model/Entities/ValidationSession.php
  lib/Alchemy/Phrasea/Model/Repositories/BasketElementRepository.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/classes/phraseadate.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/Basket.html.twig
  templates/web/prod/index.html.twig
  templates/web/prod/preview/voting_notice.html.twig
Labels: 4.1

#3741 PHRAS-3388 generate translation for tab feedback result
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/preview/voting_notice.html.twig
Labels: 4.1

#3742 PHRAS-3388: Prod - Baskets - Validation Basket - details view - add color and mailto on initiator
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/preview/voting_notice.html.twig
Labels: 4.1

#3743 PHRAS-3388 Details view validation title clickable
  templates/web/prod/preview/voting_notice.html.twig
Labels: 4.1

#3748 PHRAS-3381_tx-as-classification-plan-6_MASTER
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/lazy-3.js
  Phraseanet-production-client/dist/lazy-3.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/thesaurus/index.js
  Phraseanet-production-client/src/components/ui/workzone/index.js
  Phraseanet-production-client/src/skins/style/ui-components/_workzone-thesaurus.scss
  lib/Alchemy/Phrasea/Application/RouteLoader.php
  lib/Alchemy/Phrasea/Controller/Prod/EditController.php
  lib/Alchemy/Phrasea/Controller/Prod/ThesaurusController.php
  lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
  lib/Alchemy/Phrasea/ControllerProvider/ControllerProviderServiceProvider.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Edit.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Thesaurus.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/classes/record/adapter.php
  templates/web/prod/Thesaurus/droppedrecords.html.twig
  templates/web/prod/WorkZone/Basket.html.twig
  templates/web/prod/index.html.twig
  templates/web/prod/tab_headers.html.twig
  templates/web/thesaurus/thesaurus.html.twig
Labels: 4.1, WIP

#3749 PHRAS-3392 Worker recordEdit - apply description made by Tx as classification PHRAS-3381
  lib/Alchemy/Phrasea/Controller/Prod/EditController.php
  lib/Alchemy/Phrasea/WorkerManager/Event/RecordEditInWorkerEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/RecordEditWorker.php
Labels: 4.1

#3752 PHRAS-3400_safari-th-classification-bad-ops_MASTER
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/thesaurus/index.js
  lib/Alchemy/Phrasea/Controller/Prod/ThesaurusController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  templates/web/prod/Thesaurus/droppedrecords.html.twig
Labels: 4.1

#3754 PHRAS-3397_doubles-in-multi-values_MASTER
  lib/classes/caption/Field/Value.php
  lib/classes/record/adapter.php
Labels: 4.1

#3753 PHRAS-3399 Prod - feedback - right issue
  lib/Alchemy/Phrasea/Controller/Prod/PushController.php
  templates/web/prod/actions/Push.html.twig
Labels: 4.1

#3758 PHRAS-3405_safari-classification-bad-rollover_MASTER
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/thesaurus/index.js
  Phraseanet-production-client/src/skins/style/ui-components/_workzone-thesaurus.scss
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1

#3755 PHRAS-3146 add ttl in failed_q
  lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php
Labels: 4.1

#3759 PHRAS-3406_classification-field-centric_MASTER
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/thesaurus/index.js
  Phraseanet-production-client/src/skins/style/skin-shared.scss
  Phraseanet-production-client/src/skins/style/ui-components/_modal-classification.scss
  Phraseanet-production-client/src/skins/style/ui-components/_workzone-thesaurus.scss
  lib/Alchemy/Phrasea/Controller/Prod/ThesaurusController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  templates/web/prod/Thesaurus/droppedrecords.html.twig
Labels: 4.1

#3756 PHRAS-3399 improve ux in feedback
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/lazy-3.js
  Phraseanet-production-client/dist/lazy-3.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/record/recordPush/feedback.js
  Phraseanet-production-client/src/skins/style/ui-components/_modal-push.scss
  lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
  lib/Alchemy/Phrasea/Controller/Prod/PushController.php
  lib/Alchemy/Phrasea/Controller/Prod/ThesaurusController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/Push.html.twig
  templates/web/prod/templates/push.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Prod/PushTest.php
Labels: 4.1

#3747 PHRAS-3390 : Prod - Workzone - basket tab - local menu - "Delete" action, add "Archive" and "Cancel" choice in confirmation windows
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/basket/delete.js
  Phraseanet-production-client/src/components/ui/workzone/index.js
  Phraseanet-production-client/src/skins/style/skin-shared.scss
  lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/ExposeNew.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
Labels: 4.1, WIP

#3760 PHRAS-3399 fix initiator and button color
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/recordPush/feedback.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/Push.html.twig
  templates/web/prod/templates/push.html.twig
Labels: 4.1

#3762 PHRAS-3393_apiv3-patch-use-recordadapter_MASTER
  lib/Alchemy/Phrasea/Controller/Api/V3/V3RecordController.php
Labels: 4.1, API

#3763 PHRAS-3391 Prod - Detailed view - feedback context - add confirmation when user try to delete a Record
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/ui/workzone/index.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1
