Repository alchemy-fr/Phraseanet, pull requests merged in 2022-12, with the labels that each got.

#4180 PHRAS-2995_phr-as-auth-idp-BIS
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/ui/workzone/index.js
  composer.json
  composer.lock
  config/configuration.sample.yml
  docker-compose.under-phrasea.yml
  lib/Alchemy/Phrasea/Authentication/Provider/AbstractProvider.php
  lib/Alchemy/Phrasea/Authentication/Provider/Facebook.php
  lib/Alchemy/Phrasea/Authentication/Provider/Factory.php
  lib/Alchemy/Phrasea/Authentication/Provider/Github.php
  lib/Alchemy/Phrasea/Authentication/Provider/GooglePlus.php
  lib/Alchemy/Phrasea/Authentication/Provider/Linkedin.php
  lib/Alchemy/Phrasea/Authentication/Provider/ProviderInterface.php
  lib/Alchemy/Phrasea/Authentication/Provider/PsAuth.php
  lib/Alchemy/Phrasea/Authentication/Provider/Twitter.php
  lib/Alchemy/Phrasea/Authentication/Provider/Viadeo.php
  lib/Alchemy/Phrasea/Controller/Root/LoginController.php
  lib/Alchemy/Phrasea/Core/Provider/AuthenticationManagerServiceProvider.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/classes/patch/417PHRAS2995.php
  lib/conf.d/configuration.yml
  resources/ansible/roles/app/templates/configuration.tpl
  resources/vagrant/config/phraseanet/configuration.yml
  resources/www/account/styles/_skin.scss
  resources/www/account/styles/_variables.scss
  resources/www/authentication/styles/_variables.scss
  templates/web/login/common/macros.html.twig
  templates/web/login/index.html.twig
  templates/web/login/register.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/FacebookTest.php
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/FactoryTest.php
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/GithubTest.php
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/GooglePlusTest.php
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/LinkedinTest.php
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/ProviderTestCase.php
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/ViadeoTest.php
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-setup.yml
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-with-hosts.yml
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration.yml
  tests/Alchemy/Tests/Phrasea/Core/Event/Subscriber/Fixtures/configuration-maintenance.yml
Labels: 4.1

#4194 PHRAS-3789_psauth-auto-select-idp
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Authentication/Provider/PsAuth.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/classes/patch/417RC2PHRAS2995.php
  lib/conf.d/configuration.yml
  resources/ansible/roles/app/templates/configuration.tpl
  resources/vagrant/config/phraseanet/configuration.yml
Labels: 4.1, version-bump-back, version-bump-front

#4195 PHRAS-3788 Backport removing of depends_on , fix .env values
  .env
  docker-compose.yml
Labels: 4.1

#4193 PHRAS-3788 docker-compose removing depends_on
  .env
  docker-compose.yml
Labels: 4.1

#4191 PHRAS-3783 Prod - Order manager - add Download Expiration date
  .env
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/order/orderItem.js
  Phraseanet-production-client/src/skins/style/skin-shared.scss
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Controller/Admin/UserController.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Order.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Helper/User/Edit.php
  lib/Alchemy/Phrasea/Model/Repositories/OrderRepository.php
  lib/Alchemy/Phrasea/Notification/Mail/MailInfoOrderDelivered.php
  lib/Alchemy/Phrasea/Order/Controller/BaseOrderController.php
  lib/Alchemy/Phrasea/Order/Controller/ProdOrderController.php
  lib/Alchemy/Phrasea/Order/OrderDelivery.php
  lib/Alchemy/Phrasea/Order/OrderValidator.php
  lib/Alchemy/Phrasea/Order/ValidationNotifier/MailNotifier.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/classes/ACL.php
  lib/classes/patch/417RC3PHRAS3783.php
  lib/conf.d/bases_structure.xml
  templates/web/admin/editusers.html.twig
  templates/web/admin/user/records_list.html.twig
  templates/web/common/dialog_export.html.twig
  templates/web/prod/orders/order_item.html.twig
Labels: 4.1, version-bump-back, version-bump-front

#4196 PHRAS-3596 Prod - Expose client - filtering expose and more change due to ps expose refactoring
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/ui/workzone/index.js
  Phraseanet-production-client/src/skins/style/ui-components/_workzone-expose.scss
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  templates/web/prod/WorkZone/ExposeEdit.html.twig
  templates/web/prod/WorkZone/ExposeList.html.twig
  templates/web/prod/WorkZone/ExposeNew.html.twig
  templates/web/prod/WorkZone/ExposePermission.html.twig
  templates/web/prod/WorkZone/ExposePublicationAssets.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
Labels: 4.1, version-bump-front

#4198 PHRAS-3596 fix button position
  templates/web/prod/WorkZone/ExposePublicationAssets.html.twig
Labels: 4.1

#4199 PHRAS-3416 phraseanet localization
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4200 PHRAS-3792 including git log in builded images
  .circleci/config.yml
Labels: 4.1

#4201 PHRAS-3791_saml-logout-500
  lib/Alchemy/Phrasea/Authentication/Authenticator.php
  tests/Alchemy/Tests/Phrasea/Authentication/AuthenticatorTest.php
Labels: 4.1
