Repository alchemy-fr/Phraseanet, pull requests merged in 2023-09, with the labels that each got.

#4368 PHRAS-3890: Admin - add "auth failure" - display and purge auth failure - only for super U
  lib/Alchemy/Phrasea/Authentication/Phrasea/FailureManager.php
  lib/Alchemy/Phrasea/Controller/Admin/UserController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Users.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  resources/www/admin/images/failure.png
  templates/web/admin/auth-failure.html.twig
  templates/web/admin/tree.html.twig
Labels: 4.1

#4369 PHRAS-3903 Admin - object inspector - record index debug tools
  lib/Alchemy/Phrasea/Controller/Admin/RootController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Root.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/inspector/record-index.html.twig
  templates/web/admin/tree.html.twig
Labels: 4.1

#4372 PHRAS-3826 add mask password argument
  .github/workflows/build.yml
Labels: 4.1

#4366 PHRAS-3889 Worker - metadata write - mime/type whitelist - write metadatas only on whitelisted files
  .env
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
  lib/classes/patch/418RC6.php
  lib/conf.d/configuration.yml
Labels: 4.1, version-bump-back

#4365 PHRAS-3901 release version 4.1.8-rc6
  CHANGELOG.md
Labels: 4.1

#4373 PHRAS-3910 fix redis php extension build
  Dockerfile
Labels: 4.1

#4377 PHRAS-3914 Lightbox - mobile fix matomo url
  templates/mobile/common/matomo_analytics.html.twig
Labels: 4.1

#4376 PHRAS-3852_tiff-background-color
  composer.json
  composer.lock
  lib/Alchemy/Phrasea/Media/Subdef/Image.php
  lib/classes/databox/subdef.php
Labels: 4.1

#4379 PHRAS-3909 : Prod - Expose cli - load more publications - add pagination
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/ui/workzone/index.js
  Phraseanet-production-client/src/skins/style/ui-components/_workzone-baskets.scss
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/ExposeNew.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
Labels: 4.1, version-bump-front

#4380 PHRAS-3416 phraseanet-localization
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4378 PHRAS-3913 Prod - Shared Baskets - validation - Need to apply rights twice
  templates/web/prod/templates/push.html.twig
Labels: 4.1
