Repository alchemy-fr/Phraseanet, pull requests merged in 2023-12, with the labels that each got.

#4426 PHRAS-3947: Prod - Editing - restrict field content to thesaurus and or suggested values
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/recordEditor/index.js
  lib/Alchemy/Phrasea/Controller/Admin/FieldsController.php
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Prod/EditController.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Databox/Field/DbalDataboxFieldRepository.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/classes/databox.php
  lib/classes/databox/field.php
  lib/conf.d/bases_structure.xml
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/fields/templates.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Admin/FieldsTest.php
Labels: 4.1, version-bump-back, version-bump-front

#4433 PHRAS-3195 : Stop to generate metadata writing event on story creation or representation definition
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
Labels: 4.1

#4434 PHRAS-3520 : patch for stamp
  lib/classes/patch/418RC8PHRAS3777.php
  lib/conf.d/configuration.yml
Labels: 4.1

#4430 PHRAS-3957: editing: search in thesaurus, from the th zone
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/recordEditor/index.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  templates/web/prod/actions/edit_default.html.twig
Labels: 4.1, version-bump-front

#4440 PHRAS-3980 cmd container
  .env
  docker-compose.override.yml
  docker-compose.yml
  docker/phraseanet/fpm/entrypoint.sh
  docker/phraseanet/worker/entrypoint.sh
Labels: 4.1

#4442 PHRAS-3978 phraseanet translation
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4437 PHRAS-3974_stamper-enhance-2
  lib/Alchemy/Phrasea/Controller/Admin/DataboxController.php
  lib/Alchemy/Phrasea/Controller/Prod/ExportController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Databox.php
  lib/Alchemy/Phrasea/Model/Entities/FtpExportElement.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/ExportMailWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/FtpWorker.php
  lib/classes/collection.php
  lib/classes/record/adapter.php
  lib/classes/set/export.php
  lib/classes/set/exportftp.php
  lib/conf.d/collection_settings.xml
  templates/web/common/dialog_export.html.twig
Labels: 4.1, patch

#4444 PHRAS-3988_feedback-report-same-record
  lib/Alchemy/Phrasea/Command/Feedback/Report/FeedbackReportCommand.php
Labels: 4.1

#4445 PHRAS-3991: pre upgrade backup WIP
  .env
  docker-compose.yml
  docker/phraseanet/setup/entrypoint.sh
Labels: WIP, 4.1

#4443 PHRAS-3979: fix bin/maintenance cleaner
  lib/Alchemy/Phrasea/Command/Maintenance/CleanApiLogsCommand.php
  lib/Alchemy/Phrasea/Command/Maintenance/CleanLogDocsCommand.php
  lib/Alchemy/Phrasea/Command/Maintenance/CleanLogSearchCommand.php
  lib/Alchemy/Phrasea/Command/Maintenance/CleanLogViewCommand.php
  lib/Alchemy/Phrasea/Command/Maintenance/CleanNotificationsCommand.php
  lib/Alchemy/Phrasea/Command/Maintenance/CleanWorkerRunningJobCommand.php
Labels: 4.1

#4449 PHRAS-3996_legacy-download-remove-excel
  lib/Alchemy/Phrasea/Controller/Prod/DownloadController.php
  templates/web/common/dialog_export.html.twig
  templates/web/prod/actions/Download/prepare.html.twig
Labels: Bug, 4.1

#4452 PHRAS-3999: admin - databases - subdefinition - error 400 and 500 when create subdefinition
  lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
  templates/web/admin/subdefs.html.twig
Labels: 4.1

#4446 PHRAS-3994: clean user - email send to customer - date is wrong
  lib/Alchemy/Phrasea/Command/Maintenance/CleanUsersCommand.php
Labels: 4.1

#4450 PHRAS-3722 : bin/console records:build-subdef
  lib/Alchemy/Phrasea/Command/Record/BuildSubdefs.php
  lib/classes/record/adapter.php
Labels: 4.1
