Repository alchemy-fr/Phraseanet, pull requests merged in 2023-03, with the labels that each got.

#4261 PHRAS-3821 chown re-organisation between setup and fpm and worker
  docker/phraseanet/fpm/entrypoint.sh
  docker/phraseanet/setup/entrypoint.sh
  docker/phraseanet/worker/entrypoint.sh
Labels: WIP, 4.1

#4264 PHRAS-3819 clean webhook log
  bin/maintenance
  lib/Alchemy/Phrasea/Command/Maintenance/CleanWebhookLogsCommand.php
Labels: 4.1

#4265 PHRAS-3823 Report - command line report generator
  .dockerignore
  .gitignore
  bin/report
  lib/Alchemy/Phrasea/Command/Report/AbstractReportCommand.php
  lib/Alchemy/Phrasea/Command/Report/ConnectionsCommand.php
  lib/Alchemy/Phrasea/Command/Report/CountAssetsCommand.php
  lib/Alchemy/Phrasea/Command/Report/CountUsersCommand.php
  lib/Alchemy/Phrasea/Notification/Mail/MailReportConnections.php
  lib/Alchemy/Phrasea/Out/Module/Excel.php
  lib/Alchemy/Phrasea/Report/Report.php
  lib/Alchemy/Phrasea/Report/ReportCountAssets.php
  lib/Alchemy/Phrasea/Report/ReportDownloads.php
  lib/Alchemy/Phrasea/Report/ReportUsers.php
Labels: 4.1

#4269 PHRAS-3823 report command some fix
  lib/Alchemy/Phrasea/Command/Report/AbstractReportCommand.php
  lib/Alchemy/Phrasea/Notification/Deliverer.php
  lib/Alchemy/Phrasea/Notification/Mail/MailReport.php
  lib/Alchemy/Phrasea/Notification/Mail/MailReportConnections.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/email-template.html.twig
Labels: 4.1

#4270 PHRAS-3273 Prod - mapbox user pref - map_zoom generate an error when is memorise by mapboxgl and read by mapboxJS
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/search/geoSearch/searchGeoForm.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1

#4271 PHRAS-3823 add separator in subject report mail
  lib/Alchemy/Phrasea/Command/Report/AbstractReportCommand.php
Labels: 4.1

#4219 PHRAS-3800_xss
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/ui/workzone/facets/index.js
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3ResultHelpers.php
  lib/Alchemy/Phrasea/Controller/LightboxController.php
  lib/Alchemy/Phrasea/Controller/PermalinkController.php
  lib/Alchemy/Phrasea/Controller/Prod/PrinterController.php
  lib/Alchemy/Phrasea/Controller/Prod/RecordController.php
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Record.php
  lib/Alchemy/Phrasea/Feed/Formatter/CoolirisFormatter.php
  lib/Alchemy/Phrasea/Model/Repositories/StoryWZRepository.php
  lib/Alchemy/Phrasea/Model/Serializer/ESRecordSerializer.php
  lib/Alchemy/Phrasea/Out/Module/PDFCgu.php
  lib/Alchemy/Phrasea/Out/Module/PDFRecords.php
  lib/Alchemy/Phrasea/Search/RecordTransformer.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/classes/Bridge/Api/Youtube.php
  lib/classes/eventsmanager/notify/bridgeuploadfail.php
  lib/classes/media/Permalink/Adapter.php
  lib/classes/module/report/nav.php
  lib/classes/record/adapter.php
  lib/classes/record/preview.php
  lib/classes/set/export.php
  templates/web/prod/preview/title.html.twig
Labels: 4.1

#4266 PHRAS-3822 Prod : Improve Image WaterMarking
  lib/Alchemy/Phrasea/Media/Subdef/Image.php
  lib/Alchemy/Phrasea/Media/Subdef/OptionType/EnumButton.php
  lib/Alchemy/Phrasea/Media/Subdef/OptionType/OptionType.php
  lib/Alchemy/Phrasea/Media/SubdefGenerator.php
  lib/classes/databox/subdef.php
  lib/classes/databox/subdefsStructure.php
  templates/web/admin/subdefs.html.twig
Labels: 4.1

#4274 PHRAS-3821 chown cache repo
  docker/phraseanet/fpm/entrypoint.sh
  docker/phraseanet/setup/entrypoint.sh
  docker/phraseanet/worker/entrypoint.sh
Labels: 4.1

#4276 PHRAS-3827 Admin- users list - keep selection and page when validate or back in users edit
  lib/Alchemy/Phrasea/Controller/Admin/UserController.php
  templates/web/admin/editusers.html.twig
  templates/web/admin/users.html.twig
Labels: 4.1

#4278 PHRAS- 3823 fix date max include, add destinataire email column
  lib/Alchemy/Phrasea/Report/ReportConnections.php
  lib/Alchemy/Phrasea/Report/ReportCountAssets.php
  lib/Alchemy/Phrasea/Report/ReportDownloads.php
  lib/Alchemy/Phrasea/Report/ReportRecords.php
  lib/Alchemy/Phrasea/Report/ReportUsers.php
Labels: 4.1

#4279 PHRAS-3823 downloads report command
  bin/report
  lib/Alchemy/Phrasea/Command/Report/DownloadsCommand.php
  lib/Alchemy/Phrasea/Report/ReportDownloads.php
Labels: 4.1

#4281 PHRAS-473 Prod - advance search - display field label and other improvements
  lib/Alchemy/Phrasea/Helper/Prod.php
  templates/web/prod/index.html.twig
Labels: 4.1

#4282 PHRAS-473 add field operator
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/search/advSearch/searchAdvancedForm.js
  Phraseanet-production-client/src/components/search/index.js
  lib/Alchemy/Phrasea/Helper/Prod.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  templates/web/prod/index.html.twig
Labels: 4.1, version-bump-front

#4284 PHRAS-473 fix reset button color
  templates/web/prod/results/help.html.twig
Labels: 4.1

#4288 PHRAS-3823 add column permalink and option in report command
  lib/Alchemy/Phrasea/Command/Report/AbstractReportCommand.php
  lib/Alchemy/Phrasea/Command/Report/DataboxContentCommand.php
  lib/Alchemy/Phrasea/Command/Report/DownloadsCommand.php
  lib/Alchemy/Phrasea/Report/ReportDownloads.php
  lib/Alchemy/Phrasea/Report/ReportRecords.php
Labels: 4.1

#4289 PHRAS-3830 prod - advance search - operator for field type number
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/dist/skin-000000.css
  Phraseanet-production-client/dist/skin-000000.min.css
  Phraseanet-production-client/dist/skin-959595.css
  Phraseanet-production-client/dist/skin-959595.min.css
  Phraseanet-production-client/dist/skin-FFFFFF.css
  Phraseanet-production-client/dist/skin-FFFFFF.min.css
  Phraseanet-production-client/src/components/search/advSearch/searchAdvancedForm.js
  Phraseanet-production-client/src/components/search/index.js
  Phraseanet-production-client/src/skins/style/ui-components/_modal-advanced-search.scss
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/index.html.twig
Labels: 4.1, version-bump-front
