Repository alchemy-fr/Phraseanet, pull requests merged in 2023-11, with the labels that each got.

#4406 PHRAS-3943_download-report-tabnames
  lib/Alchemy/Phrasea/WorkerManager/Worker/DownloadAsyncWorker.php
Labels: 4.1

#4409 PHRAS-3940 translator-group-jobs
  lib/Alchemy/Phrasea/Command/Thesaurus/Translator/Action.php
  lib/Alchemy/Phrasea/Command/Thesaurus/Translator/GlobalConfiguration.php
  lib/Alchemy/Phrasea/Command/Thesaurus/Translator/Job.php
  lib/Alchemy/Phrasea/Command/Thesaurus/Translator/TranslateCommand.php
  lib/Alchemy/Phrasea/Command/Thesaurus/Translator/doc/configuration-sample.yml
Labels: Bug, 4.1

#4399 PHRAS-3917 Prod - home redirection when session end - catch more 403
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/lightbox.js
  Phraseanet-production-client/dist/lightbox.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/basket/archive.js
  Phraseanet-production-client/src/components/basket/create.js
  Phraseanet-production-client/src/components/basket/delete.js
  Phraseanet-production-client/src/components/basket/reorderContent.js
  Phraseanet-production-client/src/components/basket/update.js
  Phraseanet-production-client/src/components/lightbox/download.js
  Phraseanet-production-client/src/components/preferences/index.js
  Phraseanet-production-client/src/components/publication/index.js
  Phraseanet-production-client/src/components/record/delete.js
  Phraseanet-production-client/src/components/record/edit.js
  Phraseanet-production-client/src/components/record/export.js
  Phraseanet-production-client/src/components/record/move.js
  Phraseanet-production-client/src/components/record/print.js
  Phraseanet-production-client/src/components/record/property.js
  Phraseanet-production-client/src/components/record/publish.js
  Phraseanet-production-client/src/components/record/pushbasketModal.js
  Phraseanet-production-client/src/components/record/sharebasketModal.js
  Phraseanet-production-client/src/components/record/tools/index.js
  Phraseanet-production-client/src/components/story/create.js
  Phraseanet-production-client/src/components/story/reorderContent.js
  Phraseanet-production-client/src/components/ui/workzone/index.js
  Phraseanet-production-client/src/phraseanet-common/components/user.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1

#4352 PHRAS-3770_quarantine-enhancement
  lib/Alchemy/Phrasea/Controller/Prod/LazaretController.php
  lib/Alchemy/Phrasea/ControllerProvider/Api/V2.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Lazaret.php
  templates/web/prod/upload/lazaret.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Prod/LazaretTest.php
Labels: 4.1

#4411 PHRAS-3949_photo-editor-cant-save
  .env
  docker/nginx/root/entrypoint.sh
Labels: 4.1

#4412 PHRAS-3950 bin/maintenance clean never connected users
  lib/Alchemy/Phrasea/Command/Maintenance/CleanUsersCommand.php
Labels: 4.1

#4405 PHRAS-3668 happyscribe autosubtitle
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  lib/Alchemy/Phrasea/Core/Event/Record/RecordAutoSubtitleEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/SubtitleSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
  templates/web/prod/actions/Tools/videoEditor.html.twig
Labels: 4.1

#4414 PHRAS-3770: generate translation
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3ResultHelpers.php
  lib/Alchemy/Phrasea/Search/RecordTransformer.php
  lib/Alchemy/Phrasea/Search/StoryTransformer.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
Labels: 4.1

#4416 PHRAS-3668 subtitle notification
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  lib/Alchemy/Phrasea/Core/Event/Record/RecordAutoSubtitleEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/SubtitleSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
  lib/classes/eventsmanager/broker.php
  lib/classes/eventsmanager/notify/subtitle.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/Tools/videoEditor.html.twig
Labels: 4.1

#4385 PHRAS-3520_stamper-enhance
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Controller/Admin/CollectionController.php
  lib/Alchemy/Phrasea/Controller/Prod/DownloadController.php
  lib/Alchemy/Phrasea/Controller/Prod/ExportController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Collection.php
  lib/Alchemy/Phrasea/Order/Controller/ApiOrderController.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/DownloadAsyncWorker.php
  lib/classes/recordutils/image.php
  lib/classes/set/export.php
  templates/web/admin/collection/suggested_value.html.twig
  templates/web/common/dialog_export.html.twig
Labels: 4.1

#4418 PHRAS-3668 fix incomplete translation
  lib/Alchemy/Phrasea/WorkerManager/Worker/ShareBasketWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubtitleWorker.php
  lib/classes/eventsmanager/notify/basketwip.php
  lib/classes/eventsmanager/notify/subtitle.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
Labels: 4.1

#4419 Phras 3416 phraseanet localization
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4413 PHRAS-3945 move pusher configuration
  lib/Alchemy/Phrasea/Controller/Prod/DownloadController.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/DownloadAsyncWorker.php
  lib/conf.d/configuration.yml
Labels: 4.1

#4422 PHRAS-3966 admin - users list - add filter for "users with api application"
  lib/Alchemy/Phrasea/Helper/User/Manage.php
  lib/classes/User/Query.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/users.html.twig
Labels: 4.1

#4424 PHRAS-3966 admin users filter translation
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4420 PHRAS-2069 rescan file metadata command
  bin/console
  lib/Alchemy/Phrasea/Command/Record/BuildPermalinks.php
  lib/Alchemy/Phrasea/Command/Record/BuildSubdefs.php
  lib/Alchemy/Phrasea/Command/Record/RecordAdd.php
  lib/Alchemy/Phrasea/Command/Record/RescanFilesMetadata.php
  lib/Alchemy/Phrasea/Command/Record/RescanTechnicalDatas.php
  lib/classes/record/adapter.php
Labels: 4.1

#4425 PHRAS-3958_download-one-asset
  lib/Alchemy/Phrasea/Controller/Prod/DoDownloadController.php
  lib/Alchemy/Phrasea/Controller/Prod/DownloadController.php
  templates/web/common/dialog_export.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Prod/DoDownloadTest.php
Labels: 4.1

#4421 PHRAS-3768_feedback-report-per-record
  bin/console
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Command/Feedback/Report/Action.php
  lib/Alchemy/Phrasea/Command/Feedback/Report/ActionInterface.php
  lib/Alchemy/Phrasea/Command/Feedback/Report/ConfigurationException.php
  lib/Alchemy/Phrasea/Command/Feedback/Report/FeedbackReportCommand.php
  lib/Alchemy/Phrasea/Command/Feedback/Report/GlobalConfiguration.php
  lib/Alchemy/Phrasea/Command/Feedback/Report/MetadataAction.php
  lib/Alchemy/Phrasea/Command/Feedback/Report/StatusBitAction.php
  lib/classes/patch/418RC8PHRAS3768.php
  lib/conf.d/configuration.yml
Labels: 4.1, version-bump-back
