Repository alchemy-fr/Phraseanet, pull requests merged in 2023-10, with the labels that each got.

#4389 PHRAS-3061 Admin - subview definition - missmatch error between value set in form and slider limit
  lib/Alchemy/Phrasea/Media/Subdef/Image.php
Labels: 4.1

#4391 PHRAS-3894 : bin/maintenance clean: - Removing BETA prefix and Memory leak
  lib/Alchemy/Phrasea/Command/Maintenance/CleanLogDocsCommand.php
  lib/Alchemy/Phrasea/Command/Maintenance/CleanLogSearchCommand.php
  lib/Alchemy/Phrasea/Command/Maintenance/CleanLogViewCommand.php
Labels: 4.1

#4384 PHRAS-3921 prod - expose-cli - became compatible with Phrasea V3 keycloak and fix
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/ui/workzone/index.js
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSAdminController.php
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/Alchemy/Phrasea/PhraseanetService/Form/PSExposeConfigurationType.php
  lib/Alchemy/Phrasea/PhraseanetService/Form/PSExposeConnectionType.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/Alchemy/Phrasea/WorkerManager/Event/ExposeUploadEvent.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/ExposeSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/PullAssetsWorker.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/phraseanet-service/expose.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
Labels: 4.1, version-bump-front

#4392 PHRAS-3921 expose-cli oauth token uri compatibility v2 v3 and asset title set
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php
  templates/web/admin/phraseanet-service/expose.html.twig
Labels: 4.1

#4394 PHRAS-3933 prod - 403 "invalide search token" - after "video tools" openning
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/lazy-1.js
  Phraseanet-production-client/dist/lazy-1.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/videoEditor/index.js
  Phraseanet-production-client/src/components/videoEditor/rangeCapture.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1, version-bump-front

#4397 PHRAS-3922 show the button stop on phraseanet service pull process and feedback reminder
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSAdminController.php
  lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
Labels: 4.1

#4386 PHRAS-3928_download_async WIP ok to test
  .env
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/package-lock.json
  Phraseanet-production-client/package.json
  Phraseanet-production-client/src/components/record/export.js
  composer.json
  composer.lock
  config/configuration.sample.yml
  docker-compose.override.yml
  docker-compose.yml
  docker/phraseanet/setup/entrypoint.sh
  docker/phraseanet/worker/supervisor_conf.d/downloadAsync.conf
  lib/Alchemy/Phrasea/Controller/Prod/DoDownloadController.php
  lib/Alchemy/Phrasea/Controller/Prod/DownloadController.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/DoDownload.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Download.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Export.php
  lib/Alchemy/Phrasea/Core/Event/DownloadAsyncEvent.php
  lib/Alchemy/Phrasea/Core/PhraseaEvents.php
  lib/Alchemy/Phrasea/Model/Manipulator/TokenManipulator.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php
  lib/Alchemy/Phrasea/WorkerManager/Queue/MessagePublisher.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/ExportSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/DownloadAsyncWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/ExportMailWorker.php
  lib/classes/set/export.php
  lib/conf.d/configuration.yml
  package.json
  resources/gulp/build.js
  resources/gulp/components/vendors/pusher-js.js
  templates/web/common/dialog_export.html.twig
  templates/web/prod/actions/Download/prepare_async.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Prod/DoDownloadTest.php
  yarn.lock
Labels: 4.1, dependencies, version-bump-front

#4401 PHRAS-3939 : fix order create basket
  lib/Alchemy/Phrasea/Order/Controller/ProdOrderController.php
  templates/web/prod/orders/order_item.html.twig
Labels: 4.1

#4382 PHRAS-3900 Check TLS version use for email SMTP sending - TLS 1.0 of 1.1 deprecation
  lib/Alchemy/Phrasea/Application.php
  lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
  lib/Alchemy/Phrasea/Form/Configuration/EmailFormType.php
Labels: 4.1

#4400 PHRAS-3931_phraseanet_local_id_in_api
  lib/Alchemy/Phrasea/Controller/Api/InstanceIdAware.php
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3ResultHelpers.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3SearchController.php
  lib/Alchemy/Phrasea/ControllerProvider/Api/V1.php
  lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
  lib/Alchemy/Phrasea/Search/RecordTransformer.php
  lib/Alchemy/Phrasea/Search/StoryTransformer.php
Labels: 4.1, API

#4398 PHRAS-3934 fix videotools subtitle timeline
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/videoEditor/videoSubtitleCapture.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1, version-bump-front

#4381 PHRAS-3918_subdef-substituable-setting
  .env
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/tools/index.js
  cache/.gitkeep
  lib/Alchemy/Phrasea/Controller/Admin/SubdefsController.php
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Subdefs.php
  lib/Alchemy/Phrasea/ControllerProvider/Prod/Tools.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Media/Subdef/Image.php
  lib/classes/databox/subdef.php
  lib/classes/databox/subdefsStructure.php
  lib/classes/patch/418RC7.php
  logs/.gitkeep
  templates/web/admin/subdefs.html.twig
  templates/web/prod/actions/Tools/index.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Prod/ToolsTest.php
  tests/classes/databox/subdefTest.php
Labels: 4.1, patch, version-bump-back, version-bump-front

#4402 PHRAS-3942 4.1.8-rc7 changelog and .env typo fix
  .env
  CHANGELOG.md
Labels: 4.1
