Repository alchemy-fr/Phraseanet, pull requests merged in 2023-07, with the labels that each got.

#4328 PHRAS-3860 bin/console user:edit
  bin/console
  lib/Alchemy/Phrasea/Command/User/UserEditCommand.php
  lib/Alchemy/Phrasea/Model/Manipulator/UserManipulator.php
Labels: 4.1

#4330 PHRAS-3855 Prod - Facettes : color html tags
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/ui/workzone/facets/index.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1, version-bump-front

#4331 PHRAS-3860 Sync phraseanet root account info
  docker-compose.yml
  docker/nginx/root/entrypoint.sh
  docker/phraseanet/setup/entrypoint.sh
  docker/phraseanet/setup/init-test-install.sh
Labels: 4.1

#4332 PHRAS-3409: Prod - Edit : A user that have no right is bloqued when trying to edit
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/edit.js
  templates/web/prod/actions/edit_default.html.twig
Labels: 4.1, version-bump-front

#4333 PHRAS-3869: secure locale cookie
  lib/Alchemy/Phrasea/Controller/Root/RootController.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/PhraseaLocaleSubscriber.php
Labels: 4.1

#4337 PHRAS-3874 Prod - tools - subdefinition tab - use subdefintion label
  lib/Alchemy/Phrasea/Controller/Prod/ToolsController.php
  templates/web/prod/actions/Tools/index.html.twig
Labels: 4.1

#4338 PHRAS-3875_release_4.1.8-rc3
  .env
  CHANGELOG.md
  lib/Alchemy/Phrasea/Core/Version.php
Labels: 4.1, version-bump-back

#4339 PHRAS-3877 Fix csp for geonames, mapbox , prod
  docker/nginx/root/etc/nginx/nginx.conf
Labels: 4.1

#4340 PHRAS-3878 fix jq to latest working commit
  Dockerfile
Labels: 4.1

#4342 PHRAS-3881_browse-thesaurus-in-editing
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/edit.js
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  templates/web/prod/actions/edit_default.html.twig
Labels: 4.1, version-bump-front

#4343 PHRAS-3876 Prod - Create - Story Title fix
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/story/create.js
  lib/Alchemy/Phrasea/Controller/Prod/StoryController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/Story/Create.html.twig
  tests/Alchemy/Tests/Phrasea/Controller/Prod/StoryTest.php
Labels: 4.1, version-bump-front

#4345 Phras 3416 phraseanet localization
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4346 PHRAS-3416_story_title_translation
  resources/locales/messages.fr.xlf
Labels: 4.1

#4344 PHRAS_3883 release 4.1.8-rc4
  .env
  CHANGELOG.md
  lib/Alchemy/Phrasea/Core/Version.php
Labels: 4.1, version-bump-back

#4347 PHRAS-3882 admin - workers - filter "consumed queue"
  lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
  lib/Alchemy/Phrasea/WorkerManager/Queue/AMQPConnection.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/worker-manager/worker_queue_monitor.html.twig
Labels: 4.1

#4349 PHRAS-3796 bin/setup check:system - download , lazaret, wrong repo is checked
  lib/Alchemy/Phrasea/Command/Setup/CheckEnvironment.php
  lib/Alchemy/Phrasea/Controller/SetupController.php
  lib/Alchemy/Phrasea/Setup/Probe/FilesystemProbe.php
  lib/Alchemy/Phrasea/Setup/Requirements/FilesystemRequirements.php
  templates/web/admin/worker-manager/worker_queue_monitor.html.twig
  tests/Alchemy/Tests/Phrasea/Setup/Requirements/FilesystemRequirementsTest.php
Labels: 4.1

#4351 PHRAS-3851 Untranslated terms : in Notifications, Detailed View, Map
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/search/geoSearch/searchGeoForm.js
  lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/ShareBasketWorker.php
  lib/classes/eventsmanager/notify/basketwip.php
  lib/classes/eventsmanager/notify/validate.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/preview/title.html.twig
Labels: 4.1, version-bump-front

#4353 PHRAS-3416 phraseanet localization
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1
