Repository alchemy-fr/Phraseanet, pull requests merged in 2024-02, with the labels that each got.

#4466 PHRAS-4019: Session expires with the php default value
  .env
  docker-compose.yml
  docker/phraseanet/setup/entrypoint.sh
  lib/Alchemy/Phrasea/Core/Configuration/SessionHandlerFactory.php
Labels: 4.1

#4465 PHRAS-4018: admin - object inspector - more informations about a record
  lib/Alchemy/Phrasea/Controller/Admin/RootController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Root.php
  lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
  lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/inspector/record-detail.html.twig
  templates/web/admin/inspector/record-index.html.twig
  templates/web/admin/worker-manager/index.html.twig
Labels: 4.1

#4468 PHRAS-4018_object_inspector_translate
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4469 PHRAS-4024: worker - job in error - filling finished column
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/SearchengineSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/EditRecordWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/FtpWorker.php
Labels: 4.1

#4471 PHRAS-4019: fix destroy redis session handler
  lib/Alchemy/Phrasea/Utilities/RedisSessionHandler.php
Labels: 4.1

#4472 PHRAS-4021: Api - migration script - instance_id - monitor endpoint improvement
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
Labels: 4.1

#4475 PHRAS-4026 : js error on "change password"
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/src/components/authentication/changePassword.js
  Phraseanet-production-client/src/components/authentication/common/forms/views/error.js
  Phraseanet-production-client/src/components/authentication/register.js
  Phraseanet-production-client/src/components/authentication/registerProvider.js
  Phraseanet-production-client/src/components/authentication/renewPassword.js
  lib/Alchemy/Phrasea/Controller/Root/LoginController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  templates/web/account/change-password.html.twig
  www/scripts/common/forms/views/error.js
Labels: 4.1, version-bump-front

#4476 PHRAS-4018: admin inspector log_docs
  lib/Alchemy/Phrasea/Controller/Admin/RootController.php
  templates/web/admin/inspector/record-detail.html.twig
  templates/web/admin/inspector/record-index.html.twig
Labels: 4.1

#4477 PHRAS-4010 Add mysql8 as alternative datastore
  .env
  docker-compose.altenatives.yml
  lib/Alchemy/Phrasea/Core/Database/DatabaseMaintenanceService.php
Labels: 4.1

#4480 PHRAS-4028 webhook in POST
  lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php
  tests/Alchemy/Tests/Phrasea/WorkerManager/Worker/WebhookWorkerTest.php
Labels: 4.1

#4473 PHRAS-4023 hcaptcha in Phraseanet
  .env
  config/configuration.sample.yml
  docker/nginx/root/entrypoint.sh
  lib/Alchemy/Phrasea/Application.php
  lib/Alchemy/Phrasea/Authentication/Phrasea/FailureManager.php
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/Root/LoginController.php
  lib/Alchemy/Phrasea/Core/Configuration/RegistryFormManipulator.php
  lib/Alchemy/Phrasea/Core/Provider/AuthenticationManagerServiceProvider.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Form/Configuration/WebservicesFormType.php
  lib/classes/patch/418RC9PHRAS4023.php
  templates/web/common/macro_captcha.html.twig
  tests/Alchemy/Tests/Phrasea/ApplicationTest.php
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-with-hosts.yml
  tests/Alchemy/Tests/Phrasea/Core/Provider/AuthenticationManagerServiceProviderTest.php
Labels: 4.1, patch, version-bump-back
