Repository alchemy-fr/Phraseanet, pull requests merged in 2024-07, with the labels that each got.

#4530 PHRAS-4082: Github action - Check the push image method
  .github/workflows/build.yml
Labels: 4.1

#4532 PHRAS-4086_pdftotext-exception
  lib/Alchemy/Phrasea/Border/Manager.php
Labels: 4.1

#4526 PHRAS-4078_ExpiringRight-to-core
  bin/console
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Application.php
  lib/Alchemy/Phrasea/Command/ExpiringRights/AlertExpiringRightsCommand.php
  lib/Alchemy/Phrasea/Controller/Prod/DownloadController.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/ExpiringRightsSubscriber.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/classes/patch/419PHRAS4078.php
Labels: 4.1, version-bump-back

#4529 PHRAS-4085_data-volumes-api
  bin/maintenance
  lib/Alchemy/Phrasea/Border/Manager.php
  lib/Alchemy/Phrasea/Command/Maintenance/LazaretFilesSetSizeCommand.php
  lib/Alchemy/Phrasea/Controller/Api/V3/V3MonitorDataController.php
  lib/Alchemy/Phrasea/ControllerProvider/Api/V3.php
  lib/Alchemy/Phrasea/Model/Entities/LazaretFile.php
Labels: Enhancement, 4.1, version-bump-back

#4533 Release of 4.1.9 version
  .env
  CHANGELOG.md
Labels: 4.1

#4534 PHRAS-3416 : fix string in admin create subdef
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/subdefs.html.twig
Labels: 4.1

#4537 PHRAS-3416 create subdefinition localisation
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1
