Repository alchemy-fr/Phraseanet, pull requests merged in 2024-06, with the labels that each got.

#4512 PHRAS-4063 Phraseanet - Keycloack - refresh token implementation
  doc/others/openid-sso.md
  lib/Alchemy/Phrasea/Authentication/Provider/Openid.php
  lib/Alchemy/Phrasea/Controller/Root/LoginController.php
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php
  templates/web/prod/WorkZone/Macros.html.twig
Labels: 4.1

#4516 PHRAS-4070_rescan-meta-multi-sources
  lib/Alchemy/Phrasea/Command/Record/RescanFilesMetadata.php
  lib/classes/record/adapter.php
Labels: 4.1

#4515 PHRAS-4069: Prod - expose cli - search publication and parent publication
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/ui/workzone/index.js
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  package.json
  resources/gulp/build.js
  resources/gulp/components/vendors/select2.js
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/WorkZone/ExposeEdit.html.twig
  templates/web/prod/WorkZone/ExposeNew.html.twig
  templates/web/prod/WorkZone/Macros.html.twig
  templates/web/prod/index.html.twig
  yarn.lock
Labels: 4.1, version-bump-front

#4519 PHRAS-4069 translation for publication search
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4520 PHRAS-4073: Register form - improvement
  lib/Alchemy/Phrasea/Authentication/RegistrationService.php
  lib/classes/unicode.php
Labels: 4.1

#4513 PHRAS-4067: admin - dashboard - 500 error
  config/configuration.sample.yml
  infra/tools/stack_migration/storage_conf.sh
  lib/Alchemy/Phrasea/Command/Setup/Install.php
  lib/Alchemy/Phrasea/Controller/Api/V1Controller.php
  lib/Alchemy/Phrasea/Controller/SetupController.php
  lib/Alchemy/Phrasea/Core/Provider/MediaAlchemystServiceProvider.php
  lib/Alchemy/Phrasea/Setup/Probe/BinariesProbe.php
  lib/Alchemy/Phrasea/Setup/Requirements/BinariesRequirements.php
  lib/classes/patch/418PHRAS4067.php
  lib/conf.d/configuration.yml
  resources/ansible/roles/app/templates/configuration.tpl
  resources/vagrant/config/phraseanet/configuration.yml
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-setup.yml
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-with-hosts.yml
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration.yml
Labels: 4.1, patch

#4509 PHRAS-4062: admin users delete and request improvement
  lib/Alchemy/Phrasea/Controller/Admin/UserController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Users.php
  lib/Alchemy/Phrasea/Model/Manager/UserManager.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/user/registrations.html.twig
Labels: 4.1

#4521 PHRAS-4018 admin- inspector delete application
  lib/Alchemy/Phrasea/Controller/Admin/RootController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Root.php
  templates/web/admin/inspector/record-index.html.twig
Labels: 4.1

#4523 PHRA-3416 Translation for 4.1.8
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4524 PHRAS-4056 -fix non escaped path error in sed
  docker-compose.yml
  docker/phraseanet/worker/entrypoint.sh
Labels: 4.1

#4525 PHRAS-4077 bin/report : add group by field into download reports
  lib/Alchemy/Phrasea/Command/Report/DownloadsCommand.php
  lib/Alchemy/Phrasea/Report/ReportActions.php
Labels: 4.1

#4522 Release of 4.1.8
  .env
  CHANGELOG.md
  lib/Alchemy/Phrasea/Core/Version.php
Labels: 4.1
