Repository alchemy-fr/Phraseanet, pull requests merged in 2024-03, with the labels that each got.

#4485 PHRAS-4039 Webhook - enrich the webhook answer
  lib/Alchemy/Phrasea/Core/Event/Record/RecordEvent.php
  lib/Alchemy/Phrasea/Core/Event/Subscriber/WebhookRecordEventSubscriber.php
  lib/classes/record/adapter.php
Labels: 4.1

#4486 PHRAS-4031 Prod - Upload - quarantaine tab - substitued image remains in the interface
  templates/web/prod/upload/lazaret.html.twig
Labels: 4.1

#4464 PHRAS-4005 - update containers os
  Dockerfile
  docker/phraseanet/worker/entrypoint.sh
Labels: 4.1

#4484 PHRAS-4038 : Phraseanet - 403 on two prod pages opened simutaniously
  lib/Alchemy/Phrasea/Controller/Controller.php
Labels: 4.1

#4482 PHRAS-4033 Log_docs - log subdefinition build and write metadata - WorkerRunningJobs
  .env
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.css
  Phraseanet-production-client/dist/production.min.css
  Phraseanet-production-client/src/prod/style/main.scss
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/QueueWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Subscriber/RecordSubscriber.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/SubdefCreationWorker.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/WriteMetadatasWorker.php
  lib/classes/Session/Logger.php
  lib/classes/patch/418RC10PHRAS4033.php
  lib/conf.d/bases_structure.xml
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  resources/www/common/images/icons/subdefCreation.png
  resources/www/common/images/icons/writeMetadatas.png
  templates/web/admin/inspector/record-detail.html.twig
  templates/web/prod/preview/short_history.html.twig
Labels: 4.1, patch, version-bump-back, version-bump-front

#4490 PHRAS-4005 fix missing plugin installation
  Dockerfile
Labels: 4.1

#4488 PHRAS-3416 localisation
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4491 PHRAS-4033 fix timeline history for writemetadata and subdefinition
  lib/classes/Session/Logger.php
  lib/conf.d/bases_structure.xml
  templates/web/prod/preview/short_history.html.twig
Labels: 4.1

#4492 PHRAS-4033 fix timeline icone position
  Phraseanet-production-client/config/config.js
  Phraseanet-production-client/dist/authenticate.js
  Phraseanet-production-client/dist/authenticate.min.js
  Phraseanet-production-client/dist/commons.js
  Phraseanet-production-client/dist/commons.min.js
  Phraseanet-production-client/dist/production.css
  Phraseanet-production-client/dist/production.min.css
  Phraseanet-production-client/src/prod/style/main.scss
  lib/Alchemy/Phrasea/Twig/PhraseanetExtension.php
Labels: 4.1, version-bump-front
