Repository alchemy-fr/Phraseanet, pull requests merged in 2024-04, with the labels that each got.

#4497 PHRAS-4041:Prod - matomo - Field display - improve rendering of Matomomediametrics
  lib/Alchemy/Phrasea/Core/Provider/TwigServiceProvider.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/common/macro_caption.html.twig
Labels: 4.1

#4498 PHRAS-4041 MatomoMediaMetrics translation for json keys
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4499 PHRAS-3416 local for worker jobs
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4500 PHRAS-4056 change imagemagick version and config file path
  .env
  docker/phraseanet/worker/entrypoint.sh
Labels: 4.1

#4495 PHRAS-4049: memory allocation error - validation reminder worker in a cron job - Allowed memory size
  lib/Alchemy/Phrasea/Cache/RedisCache.php
Labels: 4.1

#4504 PHRAS-3416 phraseanet localization
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
Labels: 4.1

#4502 PHRAS-4042 fix webvtt sent to expose
  docker-compose.under-phrasea.yml
  lib/Alchemy/Phrasea/WorkerManager/Worker/ExposeUploadWorker.php
Labels: 4.1

#4506 PHRAS-4060 webhook - error - stay in running status
  lib/Alchemy/Phrasea/Webhook/Processor/SubdefEventProcessor.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/WebhookWorker.php
Labels: 4.1

#4503 PHRAS-4059: prod - user account - application cannot be deleted
  lib/Alchemy/Phrasea/Model/Manipulator/ApiApplicationManipulator.php
Labels: 4.1

#4505 PHRAS-4053 redis native session
  .env
  docker/phraseanet/php.ini.sample
  docker/phraseanet/setup/entrypoint.sh
Labels: 4.1

#4496 PHRAS-4045 Log - stdout - fix error on worker passed to igorw\get_in()
  lib/Alchemy/Phrasea/Core/Configuration/Configuration.php
  lib/Alchemy/Phrasea/Core/Configuration/HostConfiguration.php
Labels: 4.1

#4501 PHRAS-4057: log_doc - report mark as "cancel" for running_job entry
  config/configuration.sample.yml
  lib/Alchemy/Phrasea/Model/Repositories/WorkerRunningJobRepository.php
  lib/Alchemy/Phrasea/WorkerManager/Controller/AdminConfigurationController.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/AlchemyWorkerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Provider/ControllerServiceProvider.php
  lib/Alchemy/Phrasea/WorkerManager/Worker/MainQueueWorker.php
  lib/classes/patch/418RC12PHRAS4058.php
  lib/conf.d/configuration.yml
Labels: 4.1, patch

#4462 PHRAS-4007: Auth provider - add keycloak provider - openid
  .env
  config/configuration.sample.yml
  doc/others/feedback_report.md
  doc/others/openid-sso.md
  doc/others/stamper.md
  lib/Alchemy/Phrasea/Authentication/Provider/Openid.php
  lib/Alchemy/Phrasea/Authentication/RecoveryService.php
  lib/Alchemy/Phrasea/Controller/Admin/UserController.php
  lib/Alchemy/Phrasea/Controller/Root/LoginController.php
  lib/Alchemy/Phrasea/ControllerProvider/Admin/Users.php
  lib/Alchemy/Phrasea/Core/Version.php
  lib/Alchemy/Phrasea/Helper/User/Manage.php
  lib/Alchemy/Phrasea/Model/Entities/User.php
  lib/Alchemy/Phrasea/PhraseanetService/Controller/PSExposeController.php
  lib/Alchemy/Phrasea/PhraseanetService/Form/PSExposeConnectionType.php
  lib/classes/patch/418RC12PHRAS4007.php
  lib/conf.d/configuration.yml
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/admin/editusers.html.twig
  tests/Alchemy/Tests/Phrasea/Authentication/Provider/FactoryTest.php
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-setup.yml
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration-with-hosts.yml
  tests/Alchemy/Tests/Phrasea/Core/Configuration/Fixtures/configuration.yml
  tests/Alchemy/Tests/Phrasea/Core/Event/Subscriber/Fixtures/configuration-maintenance.yml
  tests/Alchemy/Tests/Phrasea/Plugin/Fixtures/PluginDir/TestPlugin/composer.lock
Labels: 4.1, patch, version-bump-back
