Repository alchemy-fr/Phraseanet, pull requests merged in 2025-03, with the labels that each got.

#4589 PHRAS-4135: Prod - Thesaurus Search - add content operator for search in editing and workzonethesaurus search add content operator
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/recordEditor/index.js
  Phraseanet-production-client/src/components/record/recordEditor/plugins/thesaurusDatasource.js
  Phraseanet-production-client/src/components/thesaurus/index.js
  lib/Alchemy/Phrasea/Controller/Thesaurus/ThesaurusXmlHttpController.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/edit_default.html.twig
  templates/web/prod/tab_thesaurus.html.twig
Labels: 4.1

#4592 PHRAS-4138 empty field restricted thesaurus
  Phraseanet-production-client/dist/production.js
  Phraseanet-production-client/dist/production.min.js
  Phraseanet-production-client/src/components/record/recordEditor/index.js
  Phraseanet-production-client/src/components/record/recordEditor/models/recordCollection.js
  lib/Alchemy/Phrasea/Controller/Prod/LanguageController.php
  resources/locales/messages.de.xlf
  resources/locales/messages.en.xlf
  resources/locales/messages.fr.xlf
  resources/locales/messages.nl.xlf
  resources/locales/validators.de.xlf
  resources/locales/validators.en.xlf
  resources/locales/validators.fr.xlf
  resources/locales/validators.nl.xlf
  templates/web/prod/actions/edit_default.html.twig
  templates/web/report/report_layout_child.html.twig
Labels: 4.1

#4597 PHRAS-4141-Report-updated_at-mismatch
  lib/Alchemy/Phrasea/Report/ReportRecords.php
Labels: 4.1

#4594 PHRAS-4140_sb-filter-for-expiringrights
  lib/Alchemy/Phrasea/Command/ExpiringRights/AlertExpiringRightsCommand.php
Labels: Enhancement, 4.1

#4598 PHRAS-4142 Release of 4.1.17
  .env
  CHANGELOG.md
  lib/Alchemy/Phrasea/Core/Version.php
Labels: 4.1

#4599 PHRAS-4146 bin/setup system:install - abort app installation if mysql db is not empty
  docker/phraseanet/setup/init-test-install.sh
  lib/Alchemy/Phrasea/Command/Setup/Install.php
Labels: 4.1

#4600 PHRAS-4148 release 4.1.18
  .env
  CHANGELOG.md
  lib/Alchemy/Phrasea/Core/Version.php
Labels: 4.1, version-bump-back
